<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>D Funciones | Estadística II &amp; Inferencia Estadística</title>
  <meta name="description" content="Curso básico de Estadística para ingeniería." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="D Funciones | Estadística II &amp; Inferencia Estadística" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Curso básico de Estadística para ingeniería." />
  <meta name="github-repo" content="Dfranzani/Estadistica_II" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="D Funciones | Estadística II &amp; Inferencia Estadística" />
  
  <meta name="twitter:description" content="Curso básico de Estadística para ingeniería." />
  

<meta name="author" content="Daniel Franzani" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estadísticos.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introducción a la Estadística</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="chapter" data-level="" data-path="talleres.html"><a href="talleres.html"><i class="fa fa-check"></i>Talleres de práctica</a></li>
<li class="chapter" data-level="1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html"><i class="fa fa-check"></i><b>1</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalos-de-confianza-concepto"><i class="fa fa-check"></i><b>1.1</b> Concepto</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalos-de-confianza-elaboracion"><i class="fa fa-check"></i><b>1.1.1</b> Elaboración</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-media"><i class="fa fa-check"></i><b>1.2</b> Intervalo de confianza para la media</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-media-varianza-conocida"><i class="fa fa-check"></i><b>1.2.1</b> Intervalo de confianza para la media de una distribución normal y varianza poblacional conocida</a></li>
<li class="chapter" data-level="1.2.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-media-varianza-desconocida"><i class="fa fa-check"></i><b>1.2.2</b> Intervalo de confianza para la media de una distribución normal y varianza poblacional desconocida</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>1.3</b> Intervalo de confianza para la diferencia de medias</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-conocidas"><i class="fa fa-check"></i><b>1.3.1</b> Intervalo de confianza para la diferencia de medias de dos distribuciones normales y varianzas poblacionales conocidas</a></li>
<li class="chapter" data-level="1.3.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-desconocidas-iguales"><i class="fa fa-check"></i><b>1.3.2</b> Intervalo de confianza para la diferencia de medias de dos distribuciones normales y varianzas poblacionales desconocidas e iguales</a></li>
<li class="chapter" data-level="1.3.3" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-desconocidas-distintas"><i class="fa fa-check"></i><b>1.3.3</b> Intervalo de confianza para la diferencia de medias de dos distribuciones normales y varianzas poblacionales desconocidas y distintas</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="04-Anexos.html"><a href="#intervalo-de-confianza-comparaci%C3%B3n-de-varianzas"><i class="fa fa-check"></i><b>1.4</b> Intervalo de confianza para la comparación de varianzas</a></li>
<li class="chapter" data-level="1.5" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#ejercicios-unidad1"><i class="fa fa-check"></i><b>1.5</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="PH.html"><a href="PH.html"><i class="fa fa-check"></i><b>2</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-concepto"><i class="fa fa-check"></i><b>2.1</b> Concepto</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-elaboracion"><i class="fa fa-check"></i><b>2.1.1</b> Elaboración</a></li>
<li class="chapter" data-level="2.1.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-errores"><i class="fa fa-check"></i><b>2.1.2</b> Errores tipo I y II</a></li>
<li class="chapter" data-level="2.1.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-procedimiento"><i class="fa fa-check"></i><b>2.1.3</b> Procedimiento de prueba</a></li>
<li class="chapter" data-level="2.1.4" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-intervalos-de-confianza"><i class="fa fa-check"></i><b>2.1.4</b> Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="PH.html"><a href="PH.html#pruebas"><i class="fa fa-check"></i><b>2.2</b> Prueba de hipótesis para la media</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-media-varianza-conocida"><i class="fa fa-check"></i><b>2.2.1</b> Prueba de hipótesis para la media de una distribución normal con varianza poblacional conocida</a></li>
<li class="chapter" data-level="2.2.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-media-varianza-desconocida"><i class="fa fa-check"></i><b>2.2.2</b> Prueba de hipótesis para la media de una distribución normal con varianza poblacional desconocida</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias"><i class="fa fa-check"></i><b>2.3</b> Prueba de hipótesis para la diferencia de medias</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-conocidas"><i class="fa fa-check"></i><b>2.3.1</b> Prueba de hipótesis para la diferencia de medias de dos distribuciones normales con varianzas poblacionales conocidas</a></li>
<li class="chapter" data-level="2.3.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-iguales"><i class="fa fa-check"></i><b>2.3.2</b> Prueba de hipótesis para la diferencia de medias de dos distribuciones normales con varianzas poblacionales desconocidas e iguales</a></li>
<li class="chapter" data-level="2.3.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-distintas"><i class="fa fa-check"></i><b>2.3.3</b> Prueba de hipótesis para la diferencia de medias de dos distribuciones normales con varianzas poblacionales desconocidas y distintas</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-comparacion-varianzas"><i class="fa fa-check"></i><b>2.4</b> Prueba de hipótesis para comparación de varianzas</a></li>
<li class="chapter" data-level="2.5" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-proporciones"><i class="fa fa-check"></i><b>2.5</b> Prueba de hipótesis para la diferencia de proporciones</a></li>
<li class="chapter" data-level="2.6" data-path="PH.html"><a href="PH.html#ejercicios-unidad2"><i class="fa fa-check"></i><b>2.6</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regresion-lineal.html"><a href="regresion-lineal.html"><i class="fa fa-check"></i><b>3</b> Regresión Lineal</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-medidas-asociacion"><i class="fa fa-check"></i><b>3.1</b> Medidas de asociación lineal</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-covarianza"><i class="fa fa-check"></i><b>3.1.1</b> Covarianza</a></li>
<li class="chapter" data-level="3.1.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-correlacion"><i class="fa fa-check"></i><b>3.1.2</b> Correlación</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>3.2</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#EMCRLS"><i class="fa fa-check"></i><b>3.2.1</b> Estimadores de mínimos cuadrados</a></li>
<li class="chapter" data-level="3.2.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#sumascuadraticas"><i class="fa fa-check"></i><b>3.2.2</b> Sumas cuadráticas</a></li>
<li class="chapter" data-level="3.2.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#pruebasHipotesisRLS"><i class="fa fa-check"></i><b>3.2.3</b> Pruebas de hipótesis</a></li>
<li class="chapter" data-level="3.2.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#metricasRLS"><i class="fa fa-check"></i><b>3.2.4</b> Métricas</a></li>
<li class="chapter" data-level="3.2.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-simple-supuestos"><i class="fa fa-check"></i><b>3.2.5</b> Supuestos</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple"><i class="fa fa-check"></i><b>3.3</b> Regresión lineal múltiple</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#EMC-RLM-CUERPO"><i class="fa fa-check"></i><b>3.3.1</b> Estimadores de mínimos cuadrados</a></li>
<li class="chapter" data-level="3.3.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#covariables-cualitativas"><i class="fa fa-check"></i><b>3.3.2</b> Covariables cualitativas</a></li>
<li class="chapter" data-level="3.3.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple-pruebas-hipotesis"><i class="fa fa-check"></i><b>3.3.3</b> Pruebas de hipótesis</a></li>
<li class="chapter" data-level="3.3.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#metricasRLM"><i class="fa fa-check"></i><b>3.3.4</b> Métricas</a></li>
<li class="chapter" data-level="3.3.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple-supuestos"><i class="fa fa-check"></i><b>3.3.5</b> Supuestos</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables"><i class="fa fa-check"></i><b>3.4</b> Selección de variables</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables-forward"><i class="fa fa-check"></i><b>3.4.1</b> Forward</a></li>
<li class="chapter" data-level="3.4.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables-backward"><i class="fa fa-check"></i><b>3.4.2</b> Backward</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-prediccion-observaciones"><i class="fa fa-check"></i><b>3.5</b> Predicción de observaciones</a></li>
<li class="chapter" data-level="3.6" data-path="regresion-lineal.html"><a href="regresion-lineal.html#ejercicios-unidad-3"><i class="fa fa-check"></i><b>3.6</b> Ejercicios</a></li>
</ul></li>
<li class="appendix"><span><b>Apéndice</b></span></li>
<li class="chapter" data-level="A" data-path="estimadores.html"><a href="estimadores.html"><i class="fa fa-check"></i><b>A</b> Estimadores</a>
<ul>
<li class="chapter" data-level="A.1" data-path="estimadores.html"><a href="estimadores.html#RLS-EMC"><i class="fa fa-check"></i><b>A.1</b> EMC en Regresión Lineal Simple</a></li>
<li class="chapter" data-level="A.2" data-path="04-Anexos.html"><a href="#descomposici%C3%B3n-de-la-suma-de-cuadrados-total"><i class="fa fa-check"></i><b>A.2</b> Descomposición de la Suma de Cuadrados Total</a></li>
<li class="chapter" data-level="A.3" data-path="estimadores.html"><a href="estimadores.html#RLM-EMC"><i class="fa fa-check"></i><b>A.3</b> EMC en Regresión Lineal Múltiple</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="04-Anexos.html"><a href="#m%C3%A9tricas"><i class="fa fa-check"></i><b>B</b> Métricas</a>
<ul>
<li class="chapter" data-level="B.1" data-path="métricas.html"><a href="métricas.html"><i class="fa fa-check"></i><b>B.1</b> <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> ajustado</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="04-Anexos.html"><a href="#estad%C3%ADsticos"><i class="fa fa-check"></i><b>C</b> Estadísticos</a>
<ul>
<li class="chapter" data-level="C.1" data-path="estadísticos.html"><a href="estadísticos.html"><i class="fa fa-check"></i><b>C.1</b> Estadístico F del método de selección Forward</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="funciones.html"><a href="funciones.html"><i class="fa fa-check"></i><b>D</b> Funciones</a>
<ul>
<li class="chapter" data-level="D.1" data-path="funciones.html"><a href="funciones.html#funcion-indicatriz"><i class="fa fa-check"></i><b>D.1</b> Esquema de la función indicatriz</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/rmarkdown-cookbook" target="blank">Published with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística II &amp; Inferencia Estadística</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="funciones" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">D</span> Funciones<a href="funciones.html#funciones" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="funcion-indicatriz" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">D.1</span> Esquema de la función indicatriz<a href="funciones.html#funcion-indicatriz" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Al trabajar con variables cualitativas, existen distintas maneras de esquematizar este tipo de variable en la matriz de diseño. Considerando una muestra de dos observaciones, para la cual se labora un modelo de regresión lineal con una sola variable independiente cualitativa de dos categorías, entonces, la matriz de diseño <span class="math inline">\(X\)</span>, tentativamente, sería de la siguiente forma.</p>
<span class="math display" id="eq:matriz-colineal">\[\begin{equation}
X = \begin{pmatrix}
1 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 \\
\end{pmatrix},
\tag{D.1}
\end{equation}\]</span>
<p>donde, la primera columna está asociada a <span class="math inline">\(\beta_0\)</span>, y la segunda y tercera están asociadas a las categorías de la variable cualitativa. La segunda columna toma el valor de 1 cuando la observación está asociada a una determinada categoría y 0 si está asociada a otra. Lo mismo ocurre para la tercera columna (que es para referirse a la otra categoría de la variable). Esta forma de ordenar las columnas para los distintos valores de la variable se denomina <strong>función indicatriz</strong>, que se especifica de la siguiente manera:</p>
<span class="math display" id="eq:funcion-indicatriz">\[\begin{equation}
I(x) = \left\lbrace\begin{matrix}
1 &amp; \text{si } x \in \text{categoría} \\
0 &amp; \text{si } x \notin \text{categoría} \\
\end{matrix}
\right.
\tag{D.2}
\end{equation}\]</span>
<p>Luego, el modelo ajustado (incorrecto) sería el siguiente.</p>
<span class="math display" id="eq:matriz-colineal-modelo">\[\begin{equation}
\widehat{Y} = \widehat{\beta}_0 + \widehat{\beta}_1I_{\text{Variable = Categoría 1}} + \widehat{\beta}_2I_{\text{Variable = Categoría 2}}
\tag{D.3}
\end{equation}\]</span>
<p>La matriz <a href="funciones.html#eq:matriz-colineal">(D.1)</a> tiene columnas linealmente dependientes, es decir, al menos una de ellas puede ser expresada como combinación lineal de las otras. En este caso, y a modo de ejemplo, es fácil ver qué</p>
<span class="math display" id="eq:colinealidad">\[\begin{equation}
C_1 = C_2 + C_3,
\tag{D.4}
\end{equation}\]</span>
<p>donde <span class="math inline">\(C_i\)</span> indica la columna de la matriz. Esto implica, que no es posible calcular los EMC expresados en la ecuación <a href="estimadores.html#eq:betasmultiple3-demostracion">(A.18)</a>, ya que, la matriz <span class="math inline">\((X^tX)\)</span> no es invertible al darse este fenómeno de dependencia, y por ende, el modelo ajustado <a href="funciones.html#eq:matriz-colineal-modelo">(D.3)</a> es incorrecto.</p>
<p>Para corregir esto, una de las soluciones más intuitivas es plantear una nueva matriz de diseño eliminando una de las columnas involucradas en la ecuación <a href="funciones.html#eq:colinealidad">(D.4)</a>. Así, ninguna de las columnas de la matriz <span class="math inline">\(X\)</span> podría ser expresada como combinación lineal de las otras, sin embargo, ¿que sucede con el parámetro asociado a la columna que se elimina?</p>
<p>Como se explica en la sección <a href="regresion-lineal.html#covariables-cualitativas">3.3.2</a>, la variable que no se observa en el modelo es la denominada categoría de referencia, que en otras palabras, es la columna que se ha eliminado de la matriz de diseño para poder calcular los EMC. Ahora, el beta asociado a la categoría (columna) que se elimina de la matriz de diseño será “absorbido” por el intercepto, es decir, <span class="math inline">\(\beta_0\)</span>. Para estudiar esto, considere dos matrices de diseño, <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span>, en la primera se ha eliminado la segunda columna, y en la segunda se ha eliminado la primera columna (la asociada al intercepto).</p>
<span class="math display" id="eq:matriz-corregidas">\[\begin{equation}
\begin{matrix}
X_1 = \begin{pmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\end{pmatrix},
&amp;
X_2 = \begin{pmatrix}
1 &amp; 0 \\
0 &amp; 1 \\
\end{pmatrix}
\end{matrix}
\tag{D.5}
\end{equation}\]</span>
<p>Las ecuaciones <a href="funciones.html#eq:ecuacion-x1">(D.6)</a> y <a href="funciones.html#eq:ecuacion-x2">(D.7)</a> corresponde a las ecuación de regresión poblacional para matriz de diseño. El superíndice sobre los residuos indica a qué modelo pertenecen.</p>
<span class="math display" id="eq:ecuacion-x1">\[\begin{equation}
Y = X_1\beta + \varepsilon^1
\tag{D.6}
\end{equation}\]</span>
<span class="math display" id="eq:ecuacion-x2">\[\begin{equation}
Y = X_2\beta + \varepsilon^2
\tag{D.7}
\end{equation}\]</span>
<p>Las ecuaciones <a href="funciones.html#eq:ecuacion-x1-lineal">(D.8)</a> y <a href="funciones.html#eq:ecuacion-x2-lineal">(D.9)</a> corresponde a la forma lineal de las ecuaciones anteriores. El subíndice 1 bajo la función indicatriz indica que la variable cualitativa está asociada a la primera categoría, y el subíndice 2 indica que está asociada a la segunda categoría.</p>
<span class="math display" id="eq:ecuacion-x1-lineal">\[\begin{equation}
Y_i = \beta_0 + \beta_1I_1 + \varepsilon_i^1
\tag{D.8}
\end{equation}\]</span>
<span class="math display" id="eq:ecuacion-x2-lineal">\[\begin{equation}
Y_i = \beta_1I_1 + \beta_2I_2 + \varepsilon_i^2
\tag{D.9}
\end{equation}\]</span>
<p>Las ecuaciones <a href="funciones.html#eq:ecuacion-x1-lineal-ajustado">(D.10)</a> corresponden a las ecuaciones <a href="funciones.html#eq:ecuacion-x2-lineal-ajustado">(D.11)</a> ajustadas al reemplazar los EMC en las ecuaciones anteriores. Cabe mencionar, que si bien el parámetro <span class="math inline">\(\beta_1\)</span> está presente en ambas ecuaciones, el EMC será distinto en cada modelo, es por ello, que lo diferenciamos con comilla, además, los residuos serán diferenciados de la misma forma los errores.</p>
<span class="math display" id="eq:ecuacion-x1-lineal-ajustado">\[\begin{equation}
Y_i = \widehat{\beta}_0 + \widehat{\beta}_1I_1 + e_i^1
\tag{D.10}
\end{equation}\]</span>
<span class="math display" id="eq:ecuacion-x2-lineal-ajustado">\[\begin{equation}
Y_i = \widehat{\beta}_1&#39;I_1 + \widehat{\beta}_2&#39;I_2 + e_i^2
\tag{D.11}
\end{equation}\]</span>
<p>Luego, igualando las ecuaciones <a href="funciones.html#eq:ecuacion-x1-lineal-ajustado">(D.10)</a> y <a href="funciones.html#eq:ecuacion-x2-lineal-ajustado">(D.11)</a> se tiene que</p>
<span class="math display" id="eq:igualando-x1-x2">\[\begin{equation}
\begin{split}
\widehat{\beta}_0 + \widehat{\beta}_1I_1 + e_i^1 &amp;= \widehat{\beta}_1&#39;I_1 + \widehat{\beta}_2&#39;I_2 + e_i^2\\
\sum_{i=1}^n\widehat{\beta}_0 + \sum_{i=1}^n\widehat{\beta}_1I_1 + \sum_{i=1}^ne_i^1 &amp;= \sum_{i=1}^n\widehat{\beta}_1&#39;I_1 + \sum_{i=1}^n\widehat{\beta}_2&#39;I_2 + \sum_{i=1}^ne_i^2\\
\sum_{i=1}^n\widehat{\beta}_0 + \sum_{i=1}^n\widehat{\beta}_1I_1 &amp;= \sum_{i=1}^n\widehat{\beta}_1&#39;I_1 + \sum_{i=1}^n\widehat{\beta}_2&#39;I_2\\
n\widehat{\beta}_0 + j\widehat{\beta}_1 &amp;= j\widehat{\beta}_1&#39; + (n-j)\widehat{\beta}_2&#39;\\
n\widehat{\beta}_0 + j\widehat{\beta}_1 &amp;= j\widehat{\beta}_1&#39; + n\widehat{\beta}_2&#39;-j\widehat{\beta}_2&#39;\\
\end{split}
\tag{D.12}
\end{equation}\]</span>
<p>donde, <span class="math inline">\(j\)</span> es la cantidad de veces que la variable cualitativa toma el valor de la primera categoría, por ende, <span class="math inline">\(n-j\)</span> es la cantidad de veces que la variable cualitativa toma el valor de la segunda categoría. Luego, igualando los elementos que acompañan a <span class="math inline">\(n\)</span> y <span class="math inline">\(j\)</span> respectivamente, se tiene las siguiente igualdades:</p>
<span class="math display" id="eq:ecuacion-x1-x2-1">\[\begin{equation}
\begin{split}
\widehat{\beta}_0 &amp;= \widehat{\beta}_2&#39;\\
\end{split}
\tag{D.13}
\end{equation}\]</span>
<span class="math display" id="eq:ecuacion-x1-x2-2">\[\begin{equation}
\begin{split}
\widehat{\beta}_1 &amp;= \widehat{\beta}_1&#39; - \widehat{\beta}_2&#39;\\
\widehat{\beta}_1 &amp;= \widehat{\beta}_1&#39; - \widehat{\beta}_0\\
\widehat{\beta}_1 + \widehat{\beta}_0 &amp;= \widehat{\beta}_1&#39;\\
\end{split}
\tag{D.14}
\end{equation}\]</span>
<p>Considerando la ecuación <a href="funciones.html#eq:ecuacion-x1-x2-1">(D.13)</a> y, reemplazando <a href="funciones.html#eq:ecuacion-x1-x2-2">(D.14)</a>, se tiene que <span class="math inline">\(\widehat{\beta}_2&#39; + \widehat{\beta}_1 = \widehat{\beta}_1&#39;\)</span>, por lo cual, el efecto propio de la primera categoría de la variable cualitativa (<span class="math inline">\(\widehat{\beta}_1&#39;\)</span>) es igual al valor del efecto propio de la segunda categoría más una diferencia, es decir, es el efecto de la primera categoría sobre la variable <span class="math inline">\(Y\)</span> respecto a la categoría de referencia. Esta igualdad se puede expresar como el efecto superior o inferior (<span class="math inline">\(\widehat{\beta}_1\)</span>) que tiene la primera categoría sobre el efecto directo de la segunda (<span class="math inline">\(\widehat{\beta}_2&#39;\)</span>).</p>
<p>A continuación, se muestra un ejemplo práctico para entender estas relaciones. La base de datos <code>iris</code> tiene la siguiente descripción en la documentación de R: “Este famoso conjunto de datos de iris (de Fisher o Anderson) proporciona las medidas en centímetros de las variables longitud y ancho del sépalo y longitud y ancho de los pétalos, respectivamente, para 50 flores de cada una de las 3 especies de iris. Las especies son Iris setosa, versicolor y virginica.”.</p>
<p>Se filtran los tipos de especies para considerar solo dos, <code>setosa</code> y <code>versicolor</code>. Luego, se plantea un modelo que utiliza el intercepto y una categoría de referencia, es decir, se hace uso de una matriz de diseño del tipo <a href="funciones.html#eq:ecuacion-x1">(D.6)</a>. La salida del modelo refleja que la categoría de referencia (columna eliminada) corresponde a <code>setosa</code>. Luego, el modelo ajustado es el siguiente.</p>
<span class="math display" id="eq:modelo-x1-ejemplo">\[\begin{equation}
\widehat{Y}_{\text{Sepal.Length}} = \widehat{\beta}_0 + \widehat{\beta}_1I_{\text{Species = versicolor}}
\tag{D.15}
\end{equation}\]</span>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="funciones.html#cb207-1" tabindex="-1"></a>datos <span class="ot">=</span> iris</span>
<span id="cb207-2"><a href="funciones.html#cb207-2" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">subset</span>(datos, Species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;setosa&quot;</span>, <span class="st">&quot;versicolor&quot;</span>))</span>
<span id="cb207-3"><a href="funciones.html#cb207-3" tabindex="-1"></a><span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Species, <span class="at">data =</span> datos)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Length ~ Species, data = datos)
## 
## Coefficients:
##       (Intercept)  Speciesversicolor  
##             5.006              0.930</code></pre>
<p>Se plantea un segundo modelo, que contiene el efecto de ambas categorías, dejando fuera el efecto del intercepto, es decir, se hace uso de una matriz de diseño del tipo <a href="funciones.html#eq:ecuacion-x2">(D.7)</a>. Se puede observar, que se tiene un valor directamente para una de la categorías (un efecto <em>propio</em> para cada una). <strong>Nota:</strong> ignorar el orden de los resultados en la salida de R.</p>
<span class="math display" id="eq:modelo-x2-ejemplo">\[\begin{equation}
\widehat{Y}_{\text{Sepal.Length}} = \widehat{\beta}_1&#39;I_{\text{Species = versicolor}} +  \widehat{\beta}_2&#39;I_{\text{Species = setosa}}
\tag{D.16}
\end{equation}\]</span>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="funciones.html#cb209-1" tabindex="-1"></a><span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> Species, <span class="at">data =</span> datos)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Length ~ -1 + Species, data = datos)
## 
## Coefficients:
##     Speciessetosa  Speciesversicolor  
##             5.006              5.936</code></pre>
<p>La tabla <a href="funciones.html#tab:tablaxx">D.1</a>, muestra la asociación de estos valores según lo expresado en las ecuaciones <a href="funciones.html#eq:ecuacion-x1-x2-1">(D.13)</a> y <a href="funciones.html#eq:ecuacion-x1-x2-2">(D.14)</a>. Se puede verificar que, el valor de <span class="math inline">\(\widehat{\beta}_1&#39; = 5.936\)</span> es igual a <span class="math inline">\(\widehat{\beta}_0 + \widehat{\beta}_1 = 5.006 + 0.930\)</span> y, que el valor de <span class="math inline">\(\widehat{\beta}_0 = 5.006\)</span> es igual a <span class="math inline">\(\widehat{\beta}_2&#39; = 5.006\)</span>. En resumen, se tienen las siguientes interpretaciones de los parámetros estimados.</p>
<ul>
<li>Observando el modelo <a href="funciones.html#eq:modelo-x1-ejemplo">(D.15)</a>:
<ul>
<li><span class="math inline">\(\widehat{\beta}_0\)</span>: Ya se mostró que este valor absorbe el efecto asociado a la categoría de referencia (<span class="math inline">\(\widehat{\beta}_2&#39;\)</span>), por lo cual, su interpretación es la siguiente. Cuando la especie de la planta no es <em>versicolor</em> (es decir, <em>setosa</em>), entonces, el valor promedio del largo del sépalo es de 5.006 cm.</li>
<li><span class="math inline">\(\widehat{\beta}_1\)</span>: Es el efecto que tiene la categoría observada (<span class="math inline">\(\widehat{\beta}_1 = \widehat{\beta}_1&#39; - \widehat{\beta}_2&#39; = 0.903\)</span>) sobre la categoría de referencia (<span class="math inline">\(\widehat{\beta}_1&#39;\)</span>), por lo cual su interpretación es la siguiente. Cuando la especie de planta es <em>versicolor</em>, entonces, el valor promedio del largo del sépalo es superior en 0.903 cm respecto a las plantas de especie <em>setosa</em>.</li>
</ul></li>
<li>Observando el modelo <a href="funciones.html#eq:modelo-x2-ejemplo">(D.16)</a>:
<ul>
<li><span class="math inline">\(\widehat{\beta}_1&#39;\)</span>: Corresponde al efecto propio de la categoría, por lo cual, su interpretación la siguiente. Cuando la especie de planta es <em>setosa</em>, entonces, el valor promedio del largo del sépalo es de 5.006 cm.</li>
<li><span class="math inline">\(\widehat{\beta}_2&#39;\)</span>: Corresponde al efecto propio de la categoría, por lo cual, su interpretación la siguiente. Cuando la especie de planta es <em>versicolor</em>, entonces, el valor promedio del largo del sépalo es de 5.936 cm.</li>
</ul></li>
</ul>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tablaxx">Tabla D.1: </span>Ejemplificación de la relación de parámetros y esquema de función indicatriz
</caption>
<tbody>
<tr>
<td style="text-align:left;">
Estimador
</td>
<td style="text-align:left;">
<span class="math inline">\(\widehat{\beta}_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\widehat{\beta}_1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\widehat{\beta}_1&#39;\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\widehat{\beta}_2&#39;\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Valor
</td>
<td style="text-align:left;">
5.006
</td>
<td style="text-align:left;">
0.930
</td>
<td style="text-align:left;">
5.936
</td>
<td style="text-align:left;">
5.006
</td>
</tr>
</tbody>
</table>
</div>
<p>Como se puede apreciar, las interpretaciones de los parámetros estimados en el modelo <a href="funciones.html#eq:modelo-x2-ejemplo">(D.16)</a> no requieren de una comparación con una de las categorías, ya que se midió el efecto por separado de cada una ellas.</p>
<p>Cabe mencionar, que la categoría de referencia que se elija no influye en las propiedades mencionadas, sin embargo, la forma en la que se esquematiza la función indicatriz puede ser distinta. En la ecuación <a href="funciones.html#eq:matriz-corregidas">(D.5)</a>, la matriz <span class="math inline">\(X_1\)</span> es la forma en la que R trabaja por defecto para asignar categorías de referencia, mientras que la matriz <span class="math inline">\(X_2\)</span> requiere ser implementada manualmente, tal como se mostró para el modelo <a href="funciones.html#eq:modelo-x2-ejemplo">(D.16)</a>; una opción distinta es la siguiente.</p>
<span class="math display" id="eq:matriz-corregida3">\[\begin{equation}
X_3 = \begin{pmatrix}
1 &amp; 1 \\
1 &amp; -1 \\
\end{pmatrix},
\tag{D.17}
\end{equation}\]</span>
<p>la cual, debería ser implementada manualmente en R.</p>
<p>Si bien existe libertad a la hora de elegir cómo trabajar la matriz de diseño, se debe tener en cuenta, que todas las matrices de diseño que evitan el problema de colinealidad implican estilos de interpretación distintos.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadísticos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": true,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": true,
    "all": false
  },
  "fontsettings": false,
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["est2+inferencia.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": null
  },
  "info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
