--- 
title: "Estadística II & Inferencia Estadística"
subtitle: ""
author: "[Daniel Franzani](https://dfranzani.github.io/website/principal/home.html)"
description: > 
  Curso básico de Estadística para ingeniería.
date: "Actualizado al `r format(Sys.Date(), '%d-%m-%Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: refs.bib
csl: apa-annotated-bibliography.csl # Gitbook
biblio-style: apalike # Latex
url: 'https://dfranzani.github.io/Estadistica_II/'
link-citations: yes
github-repo: "Dfranzani/Estadistica_II"
fontsize: 11pt
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
options(tinytex.engine_args = '-shell-escape') # Minted indent
# rmarkdown::find_pandoc(cache = TRUE, dir = "/usr/bin", version = NULL) # Pandoc versión (referencias y tablas)
library(ggplot2)
library(kableExtra)
options(kableExtra.html.bsTable = T)
library(gridExtra)
# options(tinytex.verbose = TRUE)
# screenshot HTML widgets
if (is.null(webshot:::find_phantom())) webshot::install_phantomjs()
```

```{r echo = F, results='asis'}
if (knitr::is_html_output()){
cat("# Presentación {-}","\n","El documento de Estadística II es el segundo de una serie de dos, el cual tiene un enfoque en la inferencia de información a partir de conjuntos datos, mediante la aplicación de distintas técnicas estadísticas. Este segundo documento aborda los tópicos de pruebas de hipótesis, modelos de regresión lineal simple y múltiple, haciendo uso del entorno de software R.","\n","\n")

cat("Adicionalmente, se preparó una [aplición web](https://dfranzani.github.io/App_Estadistica/) para la visualización los conceptos estadísticos de las tres unidades. Pueden dejar los comentarios y sugerencias en el [foro de la aplicación](https://github.com/Dfranzani/App_Estadistica/discussions).","\n","\n")

cat("[Enlace al documento del primer curso de Estadística: Estadística I & Estadística Descriptiva](https://dfranzani.github.io/Estadistica_I/).")
}
```

```{r echo = F, results='asis'}
if (knitr::is_html_output()){
   cat("# Talleres de práctica {-}", "\n", "A continuación, se muestra una lista de los talleres disponibles:", "\n", "\n")
   talleres = list.files(path = "material/talleres/Talleres de practica")
   talleres_pruebas = talleres[grepl(".pdf", talleres) & grepl("prueba", talleres)]
   taller_examen = talleres[grepl(".pdf", talleres) & grepl("examen", talleres)]
   talleres = talleres[grepl(".pdf", talleres) & !grepl("examen", talleres) & !grepl("prueba", talleres)]
   
   link = function(taller, tipo){
      if(length(taller) != 0){
         taller = taller[order(taller)]
         if(tipo == "Taller de práctica Examen "){
            taller = paste0("[", tipo, "](material/talleres/Talleres de practica/", taller, ")")
         } else{
            taller = paste0("[", tipo, 1:length(taller), "](material/talleres/Talleres de practica/", taller, ")")
         }
      }
      return(taller)
   }
   
   talleres = c(link(talleres, "Taller de práctica "),
                link(talleres_pruebas, "Taller de práctica Evaluación "),
                link(taller_examen, "Taller de práctica Examen "))
   
   if(length(talleres) != 0){
      for (i in 1:length(talleres)) {
         cat(paste(" -", talleres[i]), "\n")
      }
   }
}
```


```{r, echo=FALSE}
# Valor para desplegar los código de carga de bases de datos dependiendo de la salida del documento
if (knitr::is_html_output()){
  code = TRUE
} else {
  code = FALSE
}
```

