<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Unidad 2 Pruebas de hipótesis | Estadística II &amp; Inferencia Estadística</title>
  <meta name="description" content="Curso básico de Estadística para ingeniería." />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="Unidad 2 Pruebas de hipótesis | Estadística II &amp; Inferencia Estadística" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Curso básico de Estadística para ingeniería." />
  <meta name="github-repo" content="Dfranzani/Estadistica_II" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Unidad 2 Pruebas de hipótesis | Estadística II &amp; Inferencia Estadística" />
  
  <meta name="twitter:description" content="Curso básico de Estadística para ingeniería." />
  

<meta name="author" content="Prof. Daniel Franzani" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intervalos-de-confianza.html"/>
<link rel="next" href="regresion-lineal.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introducción a la Estadística</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="chapter" data-level="1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html"><i class="fa fa-check"></i><b>1</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalos-de-confianza-concepto"><i class="fa fa-check"></i><b>1.1</b> Concepto</a></li>
<li class="chapter" data-level="1.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-media"><i class="fa fa-check"></i><b>1.2</b> Intervalo de confianza para una media</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-media-varianza-conocida"><i class="fa fa-check"></i><b>1.2.1</b> Varianza poblacional conocida</a></li>
<li class="chapter" data-level="1.2.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-media-varianza-desconocida"><i class="fa fa-check"></i><b>1.2.2</b> Varianza poblacional desconocida</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>1.3</b> Intervalo de confianza para la diferencia de medias</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-conocidas"><i class="fa fa-check"></i><b>1.3.1</b> Varianzas poblacionales conocidas</a></li>
<li class="chapter" data-level="1.3.2" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-desconocidas-iguales"><i class="fa fa-check"></i><b>1.3.2</b> Varianzas poblacionales desconocidas e iguales</a></li>
<li class="chapter" data-level="1.3.3" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-para-la-diferencia-de-medias-varianzas-desconocidas-distintas"><i class="fa fa-check"></i><b>1.3.3</b> Varianzas poblacionales desconocidas y distintas</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#intervalo-de-confianza-comparacion-de-varianzas"><i class="fa fa-check"></i><b>1.4</b> Intervalo de confianza para la comparación de varianzas</a>
<ul>
<li class="chapter" data-level="" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#distribucion-f"><i class="fa fa-check"></i>Distribución F</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intervalos-de-confianza.html"><a href="intervalos-de-confianza.html#ejercicios-unidad1"><i class="fa fa-check"></i><b>1.5</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="PH.html"><a href="PH.html"><i class="fa fa-check"></i><b>2</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-concepto"><i class="fa fa-check"></i><b>2.1</b> Concepto</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-elaboracion"><i class="fa fa-check"></i><b>2.1.1</b> Elaboración</a></li>
<li class="chapter" data-level="2.1.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-errores"><i class="fa fa-check"></i><b>2.1.2</b> Errores tipo I y II</a></li>
<li class="chapter" data-level="2.1.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-procedimiento"><i class="fa fa-check"></i><b>2.1.3</b> Procedimiento de prueba</a></li>
<li class="chapter" data-level="2.1.4" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-intervalos-de-confianza"><i class="fa fa-check"></i><b>2.1.4</b> Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="PH.html"><a href="PH.html#pruebas"><i class="fa fa-check"></i><b>2.2</b> Prueba de hipótesis para una media</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-media-varianza-conocida"><i class="fa fa-check"></i><b>2.2.1</b> Varianza poblacional conocida</a></li>
<li class="chapter" data-level="2.2.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-media-varianza-desconocida"><i class="fa fa-check"></i><b>2.2.2</b> Varianza poblacional desconocida</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias"><i class="fa fa-check"></i><b>2.3</b> Prueba de hipótesis para la diferencia de medias</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-conocidas"><i class="fa fa-check"></i><b>2.3.1</b> Varianzas poblacionales conocidas</a></li>
<li class="chapter" data-level="2.3.2" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-iguales"><i class="fa fa-check"></i><b>2.3.2</b> Varianzas poblacionales desconocidas e iguales</a></li>
<li class="chapter" data-level="2.3.3" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-distintas"><i class="fa fa-check"></i><b>2.3.3</b> Varianzas poblacionales desconocidas y distintas</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-comparacion-varianzas"><i class="fa fa-check"></i><b>2.4</b> Prueba de hipótesis para comparación de varianzas</a></li>
<li class="chapter" data-level="2.5" data-path="PH.html"><a href="PH.html#prueba-de-hipotesis-diferencia-proporciones"><i class="fa fa-check"></i><b>2.5</b> Prueba de hipótesis para la diferencia de proporciones</a></li>
<li class="chapter" data-level="2.6" data-path="PH.html"><a href="PH.html#ejercicios-unidad2"><i class="fa fa-check"></i><b>2.6</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regresion-lineal.html"><a href="regresion-lineal.html"><i class="fa fa-check"></i><b>3</b> Regresión Lineal</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-medidas-asociacion"><i class="fa fa-check"></i><b>3.1</b> Medidas de asociación lineal</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-covarianza"><i class="fa fa-check"></i><b>3.1.1</b> Covarianza</a></li>
<li class="chapter" data-level="3.1.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-correlacion"><i class="fa fa-check"></i><b>3.1.2</b> Correlación</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>3.2</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#EMCRLS"><i class="fa fa-check"></i><b>3.2.1</b> Estimadores de mínimos cuadrados</a></li>
<li class="chapter" data-level="3.2.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#sumascuadraticas"><i class="fa fa-check"></i><b>3.2.2</b> Sumas cuadráticas</a></li>
<li class="chapter" data-level="3.2.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#pruebasHipotesisRLS"><i class="fa fa-check"></i><b>3.2.3</b> Pruebas de hipótesis</a></li>
<li class="chapter" data-level="3.2.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#metricasRLS"><i class="fa fa-check"></i><b>3.2.4</b> Métricas</a></li>
<li class="chapter" data-level="3.2.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-simple-supuestos"><i class="fa fa-check"></i><b>3.2.5</b> Supuestos</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple"><i class="fa fa-check"></i><b>3.3</b> Regresión lineal múltiple</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#EMC-RLM-CUERPO"><i class="fa fa-check"></i><b>3.3.1</b> Estimadores de mínimos cuadrados</a></li>
<li class="chapter" data-level="3.3.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#covariables-cualitativas"><i class="fa fa-check"></i><b>3.3.2</b> Covariables cualitativas</a></li>
<li class="chapter" data-level="3.3.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple-pruebas-hipotesis"><i class="fa fa-check"></i><b>3.3.3</b> Pruebas de hipótesis</a></li>
<li class="chapter" data-level="3.3.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#metricasRLM"><i class="fa fa-check"></i><b>3.3.4</b> Métricas</a></li>
<li class="chapter" data-level="3.3.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-multiple-supuestos"><i class="fa fa-check"></i><b>3.3.5</b> Supuestos</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables"><i class="fa fa-check"></i><b>3.4</b> Selección de variables</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables-forward"><i class="fa fa-check"></i><b>3.4.1</b> Forward</a></li>
<li class="chapter" data-level="3.4.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-seleccion-variables-backward"><i class="fa fa-check"></i><b>3.4.2</b> Backward</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#regresion-lineal-prediccion-observaciones"><i class="fa fa-check"></i><b>3.5</b> Predicción de observaciones</a></li>
<li class="chapter" data-level="3.6" data-path="regresion-lineal.html"><a href="regresion-lineal.html#ejercicios-unidad-3"><i class="fa fa-check"></i><b>3.6</b> Ejercicios</a></li>
</ul></li>
<li class="appendix"><span><b>Apéndice</b></span></li>
<li class="chapter" data-level="A" data-path="estimadores.html"><a href="estimadores.html"><i class="fa fa-check"></i><b>A</b> Estimadores</a>
<ul>
<li class="chapter" data-level="A.1" data-path="estimadores.html"><a href="estimadores.html#RLS-EMC"><i class="fa fa-check"></i><b>A.1</b> EMC en Regresión Lineal Simple</a></li>
<li class="chapter" data-level="A.2" data-path="estimadores.html"><a href="estimadores.html#descomposici%C3%B3n-de-la-suma-de-cuadrados-total"><i class="fa fa-check"></i><b>A.2</b> Descomposición de la Suma de Cuadrados Total</a></li>
<li class="chapter" data-level="A.3" data-path="estimadores.html"><a href="estimadores.html#RLM-EMC"><i class="fa fa-check"></i><b>A.3</b> EMC en Regresión Lineal Múltiple</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="métricas.html"><a href="métricas.html"><i class="fa fa-check"></i><b>B</b> Métricas</a>
<ul>
<li class="chapter" data-level="B.1" data-path="métricas.html"><a href="métricas.html#R2-no-decreciente"><i class="fa fa-check"></i><b>B.1</b> <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> ajustado</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="estadísticos.html"><a href="estadísticos.html"><i class="fa fa-check"></i><b>C</b> Estadísticos</a>
<ul>
<li class="chapter" data-level="C.1" data-path="estadísticos.html"><a href="estadísticos.html#F-forward"><i class="fa fa-check"></i><b>C.1</b> Estadístico F del método de selección Forward</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="funciones.html"><a href="funciones.html"><i class="fa fa-check"></i><b>D</b> Funciones</a>
<ul>
<li class="chapter" data-level="D.1" data-path="funciones.html"><a href="funciones.html#funcion-indicatriz"><i class="fa fa-check"></i><b>D.1</b> Esquema de la función indicatriz</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/rmarkdown-cookbook" target="blank">Published with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística II &amp; Inferencia Estadística</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PH" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Unidad 2</span> Pruebas de hipótesis<a href="PH.html#PH" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En general, las bases de datos que se trabajarán en esta sección son las siguientes:</p>
<ul>
<li><p><a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%201/imacec.csv" id="Imacec2">Imacec</a>: Contiene los datos de los valores del Imacec mensual de distintos sectores desde enero del 2018 hasta junio del 2022. Las columnas de la base de datos son las siguientes:</p>
<ul>
<li>Ano: Año de medición del Imacec.</li>
<li>Mes: Mes de medición del Imacec.</li>
<li>Mineria: Imacec del sector de minería.</li>
<li>Industria: Imacec del sector de industria.</li>
</ul>
<p>El código para cargar la base de datos en R es:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="PH.html#cb13-1" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%201/imacec.csv&quot;</span>)</span></code></pre></div></li>
<li><p><a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%202/consumidor.csv" id="ICC">ICC</a>: Contiene registros del Índice de Confianza del Consumidor (ICC). Este indicador de confianza del consumidor proporciona una indicación de la evolución futura del consumo y el ahorro de los hogares. Un indicador por encima de 100 señala un aumento en la confianza de los consumidores hacia la situación económica futura, como consecuencia de la cual son menos propensos a ahorrar y más inclinados a gastar dinero en compras importantes en los próximos 12 meses. Los valores por debajo de 100 indican una actitud pesimista hacia la evolución futura de la economía, lo que posiblemente resulte en una tendencia a ahorrar más y consumir menos.</p></li>
</ul>
<p>Las variables que contiene la base de datos son las siguientes:</p>
<ul>
<li>Locacion: lugar en donde se mide el ICC (FRA = Francia, POL = Polonia, OECD = OCDE, ESP = España, BEL = Bélgica, ITA = Italia, DEU = Alemania).</li>
<li>Mes: corresponde al mes en el que se realiza la medición del índice.</li>
<li>Ano: corresponde al año en el que se realiza la medición del índice.</li>
<li>ICC: valor del índice de confianza del consumidor.</li>
</ul>
<p>El código para cargar la base de datos en R es:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="PH.html#cb14-1" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%202/consumidor.csv&quot;</span>)</span></code></pre></div>
<div id="prueba-de-hipotesis-concepto" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Concepto<a href="PH.html#prueba-de-hipotesis-concepto" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una <strong>hipótesis estadística</strong> o simplemente <em>hipótesis</em> es una pretensión o aseveración sobre el valor de un solo parámetro (característica de la población o característica de una distribución de la población) o sobre los valores de varios parámetros <span class="citation">(<a href="#ref-Devore">Devore, 2008</a>, página 285)</span> <span class="citation">(<a href="#ref-anderson">Anderson et al., 2008</a>, página 340)</span>.</p>
<p>En cualquier cualquier problema de prueba de hipótesis, existen dos hipótesis contradictorias consideradas, la hipótesis nula y la alternativa.</p>
<p>La <strong>hipótesis nula</strong> denotada por <span class="math inline">\(H_0\)</span>, es la pretensión de que inicialmente se supone cierta (la pretensión de “creencia previa”). La <strong>hipótesis alternativa</strong> denotada por <span class="math inline">\(H_1\)</span> (o <span class="math inline">\(H_a\)</span>), es la aseveración contradictoria a <span class="math inline">\(H_0\)</span>.</p>
<p>La hipótesis nula será rechazada en favor de la hipótesis alternativa solo si la evidencia muestral sugiere que <span class="math inline">\(H_0\)</span> es falsa. Si la muestra no contradice fuertemente a <span class="math inline">\(H_0\)</span>, se continuará creyendo en la verdad de la hipótesis nula. Las dos posibles conclusiones derivadas de un análisis de prueba de hipótesis son entonces <em>rechazar</em> <span class="math inline">\(H_0\)</span> o <em>no rechazar</em> <span class="math inline">\(H_0\)</span>.</p>
<div id="prueba-de-hipotesis-elaboracion" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Elaboración<a href="PH.html#prueba-de-hipotesis-elaboracion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En algunas aplicaciones no parece obvio cómo formular la hipótesis nula y alternativa. Se debe tener cuidado en estructurar la hipótesis apropiadamente de manera que la conclusión de la prueba de hipótesis proporcione la información que el investigador o la persona encargada de tomar las decisiones desea. A partir de la situación, las pruebas de hipótesis pueden tomar tres formas (tabla <a href="PH.html#tab:hipotesis">2.1</a>), las cuales se diferencian en el desigualdad o igualdad empleada en la hipótesis alternativa.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:hipotesis">Tabla 2.1: </span>Planteamiento de las pruebas de hipótesis
</caption>
<thead>
<tr>
<th style="text-align:center;">
Caso 1
</th>
<th style="text-align:center;">
Caso 2
</th>
<th style="text-align:center;">
Caso 3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(H_0: \theta = \theta_0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_0: \theta = \theta_0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_0: \theta = \theta_0\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(H_1: \theta \neq \theta_0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_1: \theta &gt; \theta_0\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_1:\theta &lt; \theta_0\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>En diversas ocasiones, <span class="math inline">\(H_1\)</span> se conoce como la “hipótesis del investigador”, puesto que es la pretensión que al investigador en realidad le gustaría validar. La palabra <em>nulo</em> “significa sin valor”, lo que sugiere que <span class="math inline">\(H_0\)</span> es identificada como la hipótesis de ningún cambio.</p>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-54" class="example"><strong>Ejemplo 2.1  </strong></span>Considérese, que el 10% de todas las tarjetas de circuito producidas por un cierto fabricante durante un periodo de tiempo reciente estaban defectuosas. Un ingeniero ha sugerido un cambio en el proceso de producción en la creencia de que dará por resultado una proporción reducida del proceso cambiado.</p>
<p>La hipótesis alternativa (posición del investigador) es <span class="math inline">\(H_1: p &lt;0.10\)</span>, la pretensión de que la modificación del procesos redujo la proporción de las tarjetas defectuosas. Una opción natural para <span class="math inline">\(H_0\)</span> en esta situación es la pretensión contraria a la establecida en <span class="math inline">\(H_1\)</span>, es decir, <span class="math inline">\(p\geq 0.1\)</span>. En su lugar se considera <span class="math inline">\(H_0: p = 0.1\)</span> contra <span class="math inline">\(H_1: p &lt; 0.1\)</span>, tal como se expuso en la tabla anterior.</p>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-55" class="exercise"><strong>Ejercicio 2.1  </strong></span>El gerente de Danvers-Hilton Resort afirma que la cantidad media que gastan los huéspedes en un fin de semana es menos de <span class="math inline">\(\$600\)</span> dólares. Un miembro del equipo de contadores observó que en los últimos meses habían aumentado tales cantidades. El contador emplea una muestra de cuentas de fin de semana para probar la afirmación del gerente.</p>
<ol style="list-style-type: lower-alpha">
<li>¿Qué forma de hipótesis deberá usar para probar la afirmación del gerente? Explique.
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Caso 1
</th>
<th style="text-align:center;">
Caso 2
</th>
<th style="text-align:center;">
Caso 3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(H_0: \mu = 600\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_0: \mu = 600\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_0: \mu = 600\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(H_1: \mu \neq 600\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_1: \mu &gt; 600\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\(H_1:\mu &lt; 600\)</span>
</td>
</tr>
</tbody>
</table>
</div></li>
<li>¿Cuál es la conclusión apropiada cuando no se puede rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>?</li>
<li>¿Cuál es la conclusión apropiada cuando se puede rechazar la hipótesis nula <span class="math inline">\(H_0\)</span>?</li>
</ol>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-56" class="exercise"><strong>Ejercicio 2.2  </strong></span>El gerente de un negocio de venta de automóviles está pensando en un nuevo plan de bonificaciones, con objeto de incrementar el volumen de ventas. Al presente, el volumen medio de ventas es 14 automóviles por mes. El gerente desea realizar un estudio para ver si el plan de
bonificaciones incrementa el volumen de ventas. Para recolectar los datos, una muestra de vendedores venderá durante un mes bajo el nuevo plan de bonificaciones.</p>
<ol style="list-style-type: lower-alpha">
<li>Dé las hipótesis nula y alternativa más adecuadas para este estudio.</li>
<li>Comente la conclusión resultante en el caso en que <span class="math inline">\(H_0\)</span> no pueda rechazarse.</li>
<li>Comente la conclusión que se obtendrá si <span class="math inline">\(H_0\)</span> puede rechazarse.</li>
</ol>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-57" class="exercise"><strong>Ejercicio 2.3  </strong></span>Debido a los costos y al tiempo de adaptación de la producción, un director de fabricación antes de implantar un nuevo método de fabricación, debe convencer al gerente de que ese nuevo método de fabricación reducirá los costos. El costo medio del actual método de producción es <span class="math inline">\(\$220\)</span> por hora. En un estudio se medirá el costo del nuevo método durante un periodo muestral de producción,</p>
<ol style="list-style-type: lower-alpha">
<li>Dé las hipótesis nula y alternativa más adecuadas para este estudio.</li>
<li>Haga un comentario sobre la conclusión cuando <span class="math inline">\(H_0\)</span> no pueda rechazarse.</li>
<li>Dé un comentario sobre la conclusión cuando <span class="math inline">\(H_0\)</span> pueda rechazarse.</li>
</ol>
</div>
</div>
<div id="prueba-de-hipotesis-errores" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Errores tipo I y II<a href="PH.html#prueba-de-hipotesis-errores" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Las hipótesis nula y alternativa son afirmaciones opuestas acerca de la población. Una de las dos, ya sea la hipótesis nula o la alternativa es verdadera, pero no ambas. Lo ideal es que la prueba de hipótesis lleve a la aceptación de <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_0\)</span> sea verdadera y al rechazo de <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_1\)</span> sea verdadera. Por desgracia, las conclusiones correctas no siempre son posibles. Como la prueba de hipótesis se basa en una información muestral debe tenerse en cuenta que existe la posibilidad de error.</p>
<p>Los dos tipos de errores que se pueden cometer son:</p>
<ul>
<li><strong>Error tipo I:</strong> Rechazar <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_0\)</span> es verdadera.</li>
<li><strong>Error tipo II:</strong> No rechazar <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_0\)</span> es falsa.</li>
</ul>
<p>Es posible el error que se desea cometer, es decir, es posible establecer la probabilidad de cometer un error tipo I o II, pero no ambos. El <strong>nivel de significancia</strong> es la probabilidad de cometer un error tipo I cuando la hipótesis nula es verdadera. Para denotar el nivel de significancia se usa la letra griega <span class="math inline">\(\alpha\)</span>, y los valores que se suelen usar para <span class="math inline">\(\alpha\)</span> con 0.05 y 0.01.</p>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-58" class="example"><strong>Ejemplo 2.2  </strong></span>Walter Williams, columnista y profesor de economía en la universidad George Mason indica que siempre existe la posibilidad de cometer un error tipo I o un error tipo II al tomar una decisión (<em>The Cincinnati Enquirer</em>, 14 de agosto de 2005). Hace notar que la Food and Drug Administration corre el riesgo de cometer estos errores en sus procedimientos para la aprobación de medicamentos.</p>
<p>Cuando comete un error tipo I, la FDA no aprueba un medicamento que es seguro y efectivo. Al cometer un error tipo II, la FDA aprueba un medicamento que presenta efectos secundarios imprevistos. Sin importar la decisión que se tome, la probabilidad de cometer un error costoso no se puede eliminar.</p>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-59" class="exercise"><strong>Ejercicio 2.4  </strong></span>Nielsen informó que los hombres jóvenes estadounidenses ven diariamente 56.2 minutos de televisión en las horas de mayor audiencia (<em>The Wall Street Journal Europe</em>, 18 de noviembre de 2003). Un investigador cree que en Alemania, los hombres jóvenes ven más tiempo la televisión en las horas de mayor audiencia. Este investigador toma una muestra de hombres jóvenes alemanes y registra el tiempo que ven televisión en un día. Los resultados muestrales se usan para probar las siguientes hipótesis nula y alternativa.</p>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
H_0&amp;: \mu = 56.2\\
H_1&amp;: \mu &gt; 56.2\\
\end{split}
\end{equation}\]</span>
<ol style="list-style-type: lower-alpha">
<li>En esta situación, ¿cuál es el error tipo I? ¿Qué consecuencia tiene cometer este error?</li>
<li>En esta situación, ¿cuál es el error tipo II? ¿Qué consecuencia tiene cometer este error?</li>
</ol>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-60" class="exercise"><strong>Ejercicio 2.5  </strong></span>Suponga que se va a implantar un nuevo método de producción si mediante una prueba de hipótesis se confirma la conclusión de que el nuevo método de producción reduce el costo medio de operación por hora.</p>
<ol style="list-style-type: lower-alpha">
<li>Dé las hipótesis nula y alternativa adecuadas si el costo medio de producción actual por hora es <span class="math inline">\(\$220\)</span>.</li>
<li>En esta situación, ¿cuál es el error tipo I? ¿Qué consecuencia tiene cometer este error?</li>
<li>En esta situación, ¿cuál es el error tipo II? ¿Qué consecuencia tiene cometer este error?</li>
</ol>
</div>
</div>
<div id="prueba-de-hipotesis-procedimiento" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Procedimiento de prueba<a href="PH.html#prueba-de-hipotesis-procedimiento" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Un procedimiento de prueba es un regla, basada en datos muestrales, para decidir si rechazar <span class="math inline">\(H_0\)</span>. Este proceso consta de dos elementos:</p>
<ul>
<li><strong>Estadístico de prueba:</strong> Función de los datos muestrales en los cuales ha de basarse la decisión.</li>
<li><strong>Región de rechazo:</strong> Conjunto de todos los valores estadísticos de prueba por los cuales <span class="math inline">\(H_0\)</span> será rechazada.</li>
</ul>
<p>Para decidir si <span class="math inline">\(H_0\)</span> es finalmente rechazada es posible ocupar dos métodos.</p>
<ol style="list-style-type: decimal">
<li><strong>Método del valor p</strong></li>
</ol>
<p>Un valor-p es una probabilidad que porta a una medida de evidencia suministrada por la muestra contra la hipótesis nula. Valores pequeños indican una evidencia mayor contra la hipótesis nula.</p>
<p>Además de representar un probabilidad, el valor-p puede ser vista como una porción de área bajo la curva. La figura <a href="PH.html#fig:graficovalorp">2.1</a> muestra la relación entre los distintos elementos ya mencionados.</p>
<p>La curva corresponde a la función de probabilidad de los datos. Los valores centrales son aquellos que son más probables de observar (parte más alta de la curva), mientras que los valores extremos (derecha e izquierda) son los menos probables de observar. El punto de color rojo corresponde al estadístico de prueba, función que nos dará un valor con el que seremos capaces de rechazar o no <span class="math inline">\(H_0\)</span>. Finalmente el área de color verde corresponde al área bajo la curva desde el estadístico observado hacia la izquierda (en este caso).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:graficovalorp"></span>
<img src="material/img/Valor_p.png" alt="Estadístico de prueba para un prueba altenativa con signo $&gt;$" width="70%" />
<p class="caption">
Figura 2.1: Estadístico de prueba para un prueba altenativa con signo <span class="math inline">\(&gt;\)</span>
</p>
</div>
<p>La tabla <a href="PH.html#tab:regiones">2.2</a>, da cuenta de la relación que existe entre las pruebas de hipótesis y la ubicación del valor-p en el gráfico presentado.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:regiones">Tabla 2.2: </span>Hipótesis alternativa, valor-p y estadístico de prueba
</caption>
<thead>
<tr>
<th style="text-align:center;">
Signo de comparación en <span class="math inline">\(H_1\)</span>
</th>
<th style="text-align:center;">
Referencia
</th>
<th style="text-align:center;">
Ubicación del estadístico de prueba y valor-p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(&gt;\)</span>
</td>
<td style="text-align:center;">
Unilateral derecha
</td>
<td style="text-align:center;">
A la derecha del gráfico
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(&lt;\)</span>
</td>
<td style="text-align:center;">
Unilateral izquierda
</td>
<td style="text-align:center;">
A la izquierda del gráfico
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\neq\)</span>
</td>
<td style="text-align:center;">
Bilateral
</td>
<td style="text-align:center;">
A ambos lados del gráfico
</td>
</tr>
</tbody>
</table>
</div>
<p>La regla de rechazo usando el valor-p es</p>
<p><span class="math display">\[\text{Rechazar } H_0 \text{ si el valor-p } \leq \alpha\]</span></p>
<p>En la figura <a href="PH.html#fig:regiones3">2.2</a>, se puede observar los tres casos posibles para las distintas hipótesis alternativas, en las cuales se ejemplifica un valor-p en cada uno de los casos. De izquierda a derecha, las hipótesis alternativas correspondientes son unilateral izquierda, unilateral derecha, y bilateral.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:regiones3"></span>
<img src="est2+inferencia_files/figure-html/regiones3-1.png" alt="Valores -p por tipo de hipótesis alternativa" width="576" />
<p class="caption">
Figura 2.2: Valores -p por tipo de hipótesis alternativa
</p>
</div>
<p>La decisión de si en cada uno de los casos se rechaza o no la hipótesis nula, depende del valor elegido para la significancia. En la figura <a href="PH.html#fig:areas-rechazo-ud">2.3</a> se muestra la comparativa entre el valor-p y <span class="math inline">\(\alpha\)</span> para el caso de una hipótesis alternativa unilateral derecha; el área sombreada de color rojo corresponde al valor de <span class="math inline">\(\alpha\)</span> (<strong>área de rechazo</strong>), mientras que el área sombreada de color gris corresponde al valor-p definido por el estadístico de prueba.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:areas-rechazo-ud"></span>
<img src="est2+inferencia_files/figure-html/areas-rechazo-ud-1.png" alt="Comparativa del valor-p y el área de rechazo para una prueba unilateral derecha" width="576" />
<p class="caption">
Figura 2.3: Comparativa del valor-p y el área de rechazo para una prueba unilateral derecha
</p>
</div>
<p>Cabe recordar que, el valor de alfa (valor del área roja en la figura <a href="PH.html#fig:areas-rechazo-ud">2.3</a>) estará dado por el investigador (subjetivo), mientras que el valor del área gris se debe determinar a partir de los datos de la muestra (estadístico de prueba).</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Método del valor crítico</strong></li>
</ol>
<p>Este método consiste en comparar el estadístico de prueba con un número fijo llamado <strong>valor crítico</strong>. El valor crítico es un punto de referencia para determinar si el valor del estadístico de prueba es lo suficientemente pequeño para rechazar la hipótesis nula. El valor
crítico corresponde a la coordenada del eje horizontal que define el área llamada <span class="math inline">\(\alpha\)</span> (fijado por el investigador), y está ubicada en el mismo sector que el valor-p. </p>
<p>El intervalo de números generado a partir del valor crítico es lo denominado <strong>región de rechazo</strong>. En la figura <a href="PH.html#fig:region-rechazo-1">2.4</a>, se observa que una hipótesis nula es rechazada cuando el valor-p es menor o igual a <span class="math inline">\(\alpha\)</span>, lo cual, es equivalente a decir que (gráfico de la izquierda), el estadístico de prueba (1.4) es mayor o igual al valor crítico (0.8), a esto se le denomina “caer en la región de rechazo”. El razonamiento de rechazo utilizando el valor crítico depende de la zona en la que se ubica alfa y el valor-p.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:region-rechazo-1"></span>
<img src="est2+inferencia_files/figure-html/region-rechazo-1-1.png" alt="Método del valor crítico para una hipótesis unilateral derecha" width="480" />
<p class="caption">
Figura 2.4: Método del valor crítico para una hipótesis unilateral derecha
</p>
</div>
<p>Los lineamientos de cómo construir un estadístico de prueba, determinar el varlo crítico y el valor-p asociados a una prueba de hipótesis, se darán a conocer a partir de la sección <a href="PH.html#pruebas">2.2</a>.</p>
</div>
<div id="prueba-de-hipotesis-intervalos-de-confianza" class="section level3 hasAnchor" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Intervalos de confianza<a href="PH.html#prueba-de-hipotesis-intervalos-de-confianza" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Existe un relación directa entre las pruebas de hipótesis y los intervalos de confianza, ya que estos pueden ser utilizados para rechazar o no <span class="math inline">\(H_0\)</span>. La tabla <a href="PH.html#tab:ICpruebas">2.3</a>, da cuenta de del tipo de intervalo de confianza que se debe elaborar para cada tipo de prueba de hipótesis.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ICpruebas">Tabla 2.3: </span>Hipótesis alternativa e Intervalo de confianza
</caption>
<thead>
<tr>
<th style="text-align:center;">
Signo de comparación en <span class="math inline">\(H_1\)</span>
</th>
<th style="text-align:center;">
Tipo de intervalo de confianza
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
<span class="math inline">\(&gt;\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\((a,\infty )\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(&lt;\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\((-\infty ,b)\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;">
<span class="math inline">\(\neq\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\((a,b)\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>A lo largo de las distintas pruebas, se abordarán los distintos métodos de prueba, incluyendo el uso de intervalos de confianza.</p>
</div>
</div>
<div id="pruebas" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Prueba de hipótesis para una media<a href="PH.html#pruebas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Esta sección se centra en el planteamiento y prueba de hipótesis relacionadas a la parámetro de media. Para cada uno de estos casos, se detalla el procedimiento en R y los distintos métodos de prueba para la decisión de rechazo de <span class="math inline">\(H_0\)</span>. En particular, las pruebas para este parámetro requieren que la distribución poblacional de la variable de estudio es normal, lo cual, se asumirá en los enunciados de los ejercicios y/o ejemplos según corresponda.</p>
<div id="prueba-de-hipotesis-media-varianza-conocida" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Varianza poblacional conocida<a href="PH.html#prueba-de-hipotesis-media-varianza-conocida" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Aun cuando la suposición de que el valor de <span class="math inline">\(\sigma^2\)</span> es conocido, rara vez se cumple en la práctica. Este caso proporciona un buen punto de partida debido a la facilidad con que los procedimientos generales y sus propiedades pueden ser desarrollados. La hipótesis nula en los tres casos propondrá que <span class="math inline">\(\mu\)</span> tiene un valor numérico particular, el valor nulo, el cual será denotado por <span class="math inline">\(\mu_0\)</span>.</p>
<p>El estadístico de prueba y los valores críticos de comparación están dados en la tabla <a href="PH.html#tab:unamedia1">2.4</a>.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unamedia1">Tabla 2.4: </span>Método del valor crítico para la prueba de una media con varianza poblacional conocida
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: \mu = \mu_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(Z_0 = \displaystyle\frac{\bar{x}-\mu_0}{\sigma/\sqrt{n}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \neq \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|Z_0| \geq Z_{1-\alpha/2}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \gt \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \geq Z_{1-\alpha}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \lt \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \leq Z_{\alpha}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-61" class="example"><strong>Ejemplo 2.3  </strong></span>El índice Rockwell de dureza para acero se determina al presionar una punta de diamante en el acero y medir la profundidad de la penetración, el cual tiene un varianza de medición de 6. Para 50 especímenes de una aleación de acero, el índice Rockwell de dureza promedió 62. El fabricante dice que esta aleación tiene un índice de dureza promedio menor a 64. Asumiendo que el índice de dureza sigue una distribución normal, ¿hay suficiente evidencia para refutar lo dicho por el fabricante con un nivel de significancia de 1%?</p>
<p>Al plantear la prueba de hipótesis se debe tener en cuenta que la hipótesis del investigador ha de estar reflejada en <span class="math inline">\(H_1\)</span>, tal como se muestra a continuación.</p>
<ul>
<li><span class="math inline">\(\mu\)</span>: media del índice de dureza de la aleación de acero.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
H_0&amp;: \mu = 64\\
H_1&amp;: \mu &lt; 64
\end{split}
\end{equation}\]</span>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="PH.html#cb15-1" tabindex="-1"></a><span class="co"># Cálculo del estadístico de prueba</span></span>
<span id="cb15-2"><a href="PH.html#cb15-2" tabindex="-1"></a>z0 <span class="ot">=</span> (<span class="dv">62-64</span>)<span class="sc">/</span>(<span class="fu">sqrt</span>(<span class="dv">6</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">50</span>))</span>
<span id="cb15-3"><a href="PH.html#cb15-3" tabindex="-1"></a>z0</span></code></pre></div>
<pre><code>## [1] -5.773503</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="PH.html#cb17-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb17-2"><a href="PH.html#cb17-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fu">pnorm</span>(z0)</span>
<span id="cb17-3"><a href="PH.html#cb17-3" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 3.882018e-09</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="PH.html#cb19-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb19-2"><a href="PH.html#cb19-2" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.01</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 3.88 <span class="math inline">\(\times 10^{-9}\)</span> es menor o igual a la significancia del 0.01, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que la media del índice de dureza de la aleación de acero es menor a 64. Considerando una confianza del 99%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>En caso de que deseemos utilizar el método del valor-p, es necesario apoyarnos en R para realizar el calculo de este. El comando necesario para calcular el valor depende la prueba que estemos llevando a cabo, por lo que en el siguiente <a href="material/resumenes/Rechazo.pdf">documento</a> podrán encontrar un resumen para las distintas pruebas.</p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(Z_0 \leq Z_{\alpha}\)</span>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="PH.html#cb21-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb21-2"><a href="PH.html#cb21-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.01</span>)</span>
<span id="cb21-3"><a href="PH.html#cb21-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] -2.326348</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="PH.html#cb23-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb23-2"><a href="PH.html#cb23-2" tabindex="-1"></a>z0 <span class="sc">&lt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El valor del estadístico de prueba de -5.7735 es menor o igual al valor crítico de -2.3263, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que la media del índice de dureza de la aleación de acero es menor a 64. Considerando una confianza del 99%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Al igual que el valor-p, la forma en la que se debe usar el intervalo de confianza varía dependiendo del tipo de prueba de hipótesis que se realiza, por lo que en el siguiente <a href="material/resumenes/hipotesis+ic.pdf">documento</a> podrán encontrar un resumen para las distintas pruebas, dicho documento incluye los distintos comando en R para obtener los resultados de una prueba de hipótesis de manera automática.</p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\mu_0 \notin\)</span> IC.</p>
<p>El intervalo de confianza a construir es:</p>
<span class="math display">\[\begin{equation}
  \notag
  \left(-\infty, \bar{x} + Z_{1-\alpha}\frac{\sigma}{\sqrt{n}}\right)
\end{equation}\]</span>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="PH.html#cb25-1" tabindex="-1"></a><span class="co"># Cálculo de los límites del intervalo de confianza</span></span>
<span id="cb25-2"><a href="PH.html#cb25-2" tabindex="-1"></a>Limite_superior <span class="ot">=</span> <span class="dv">62</span> <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.99</span>)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">6</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">50</span>)</span>
<span id="cb25-3"><a href="PH.html#cb25-3" tabindex="-1"></a>Limite_superior</span></code></pre></div>
<pre><code>## [1] 62.80587</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="PH.html#cb27-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb27-2"><a href="PH.html#cb27-2" tabindex="-1"></a><span class="dv">64</span> <span class="sc">&gt;</span> Limite_superior</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((-\infty, 62.8058)\)</span> no contiene al valor de <span class="math inline">\(\mu_0 = 64\)</span>, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que la media del índice de dureza de la aleación de acero es menor a 64. Considerando una confianza del 99%.</p></li>
</ol>
</div>
</div>
<p>Para este tipo de pruebas, no hay comandos en R que permitan hacer el trabajo de manera automática. Esto es debido a lo expuesto en un principio: <strong>difícilmente se conoce la varianza poblacional en la práctica</strong>.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-62" class="exercise"><strong>Ejercicio 2.6  </strong></span>Sea el estadístico de prueba <span class="math inline">\(Z_0\)</span> con una distribución normal estándar cuando <span class="math inline">\(H_0\)</span> es verdadera. Dé el nivel de significación en cada una de las siguientes situaciones:</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(H_1: \mu &gt; \mu_0\)</span>, región de rechazo <span class="math inline">\(Z_0\geq 1.88\)</span>.</li>
<li><span class="math inline">\(H_1: \mu &lt; \mu_0\)</span>, región de rechazo <span class="math inline">\(Z_0\leq -2.75\)</span>.</li>
<li><span class="math inline">\(H_1: \mu \neq \mu_0\)</span>, región de rechazo <span class="math inline">\(Z_0\geq 2.88\)</span> o <span class="math inline">\(Z_0\leq -2.88\)</span>.</li>
</ol>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-63" class="exercise"><strong>Ejercicio 2.7  </strong></span>Un fabricante de cajas de cartón afirma que sus cajas tienen un peso promedio de 5 kg. Para verificar esta afirmación, un cliente selecciona al azar 25 cajas y encuentra que el peso promedio es de 4.8 kg con una desviación estándar conocida de 0.5 kg. ¿Hay suficiente evidencia para rechazar la afirmación del fabricante al nivel de significancia del 5%?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-64" class="exercise"><strong>Ejercicio 2.8  </strong></span>Se sabe que la duración de las baterías sigue una distribución normal con media 290 horas y varianza poblacional conocida de 64 horas. Bajo una nueva fórmula de fabricación, se tomó una muestra aleatoria de 36 dispositivos móviles y se registró una duración media muestral de 280 horas. Utilizando un nivel de significancia del 5%, ¿se puede concluir con suficiente evidencia estadística que la duración media de las baterías ha mejorado significativamente después de aplicar una nueva fórmula en su fabricación?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-65" class="exercise"><strong>Ejercicio 2.9  </strong></span>Un cirujano necesita evaluar si los pacientes se recuperan en un promedio en un tiempo menor a 5 días después de una cirugía. Para probar su afirmación, un internista toma una muestra aleatoria de 20 pacientes y encuentra que la duración promedio de recuperación es de 6 días, con una desviación estándar conocida de 1.5 días. ¿Hay suficiente evidencia para rechazar la afirmación del cirujano al nivel de significancia del 10%?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-66" class="exercise"><strong>Ejercicio 2.10  </strong></span>Se requiere estudiar si la cantidad promedio de cafeína en una taza de café es menor a 100 mg. Para probar esta hipótesis, se toma una muestra aleatoria de 50 tazas de café y se encuentra que la cantidad promedio de cafeína es de 105 mg, con una desviación estándar conocida de 15 mg. ¿Hay suficiente evidencia para rechazar la hipótesis nula al nivel de significancia del 5%?</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-67" class="exercise"><strong>Ejercicio 2.11  </strong></span>Se desea evaluar si la altura promedio de una población de girasoles es distinta de 150 cm. Para ello, se selecciona una muestra aleatoria de 30 girasoles y se encuentra que la altura promedio es de 155 cm, con una desviación estándar conocida de 5 cm. ¿Hay suficiente evidencia para rechazar la hipótesis nula al nivel de significancia del 1%?</p>
</div>
</div>
<div id="prueba-de-hipotesis-media-varianza-desconocida" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Varianza poblacional desconocida<a href="PH.html#prueba-de-hipotesis-media-varianza-desconocida" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De igual manera a lo expuesto en el primer caso, los pasos a seguir para probar una hipótesis son los mismos, y se mantendrá así para cualquier caso.</p>
<ol style="list-style-type: decimal">
<li>Plantear las hipótesis nula y alternativa</li>
<li>Identificar o establecer el nivel de significancia.</li>
<li>Identificar los datos muestrales y poblacionales con los que se cuenta.</li>
<li>Utilizar alguna de las reglas de decisión (Estadístico de prueba, valor-p o intervalo de confianza).</li>
<li>Concluir</li>
</ol>
<p>En la situación de una prueba de hipótesis de la media, en la cual lo datos distribuyen normal y la varianza poblacional es desconocida, los criterios de rechazo son similares a los vistos anteriormente, sin embargo, cambia la distribución del estadístico de prueba, tal como se muestra en la tabla <a href="PH.html#tab:unamedia2">2.5</a>.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unamedia2">Tabla 2.5: </span>Método del valor crítico para la prueba de una media con varianza poblacional desconocida
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: \mu = \mu_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(t_0 = \displaystyle\frac{\bar{x}-\mu_0}{S/\sqrt{n}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \neq \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|t_0| \geq t_{1-\alpha/2, n-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \gt \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \geq t_{1-\alpha,n-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu \lt \mu_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \leq t_{\alpha,n-1}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>donde <span class="math inline">\(n\)</span> corresponde al tamaño de la muestra.</p>
<div class="blackbox">
<div class="example">
<p><span id="exm:imacec" class="example"><strong>Ejemplo 2.4  </strong></span>Utilizando la base de datos <a href="PH.html#Imacec2">Imacec</a>, establezca si hay suficiente evidencia estadística para afirmar que, el valor promedio del Imacec de cada sector por separado es mayor a 98.54167 (denote este valor por <span class="math inline">\(\mu_0\)</span>). Establezca las hipótesis respectivas, estadísticos y criterios de rechazo, utilizando una significancia del 10%. Asuma que las variables distribuyen normal y tienen varianza poblacional desconocida.</p>
<p>En este caso al contar con una base de datos (y para este tipo de prueba), podemos hacer uso directamente de R para obtener el estadístico de prueba, valor-p e intervalo de confianza asociado.</p>
<p>Iniciamos con la prueba de hipótesis para el sector de minería.</p>
<ul>
<li><span class="math inline">\(\mu:\)</span> Media del Imacec de Minería.</li>
</ul>
<span class="math display">\[\begin{equation}
    \notag
    \begin{split}
        H_0: \mu = 98.54167\\
        H_1: \mu &gt; 98.54167
    \end{split}
\end{equation}\]</span>
<p>Luego, haciendo uso de R obtenemos los elementos necesario para rechazar o no <span class="math inline">\(H_0\)</span>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="PH.html#cb29-1" tabindex="-1"></a><span class="co"># Cargue previamente la base de datos, guardándola con el nombre &quot;df&quot;</span></span>
<span id="cb29-2"><a href="PH.html#cb29-2" tabindex="-1"></a><span class="co"># Minería</span></span>
<span id="cb29-3"><a href="PH.html#cb29-3" tabindex="-1"></a><span class="fu">t.test</span>( <span class="co"># Prueba de hipótesis para el estadístico con distribución t-student</span></span>
<span id="cb29-4"><a href="PH.html#cb29-4" tabindex="-1"></a>  <span class="at">x =</span> df<span class="sc">$</span>Mineria, <span class="co"># Valores del Imacec de Minería</span></span>
<span id="cb29-5"><a href="PH.html#cb29-5" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="co"># Signo de desigualdad de la hipótesis alternativa</span></span>
<span id="cb29-6"><a href="PH.html#cb29-6" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fl">98.54167</span>, <span class="co"># Valor del Mu_0</span></span>
<span id="cb29-7"><a href="PH.html#cb29-7" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.9</span> <span class="co"># Confianza = 1 - alfa</span></span>
<span id="cb29-8"><a href="PH.html#cb29-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$Mineria
## t = -1.2773, df = 53, p-value = 0.8965
## alternative hypothesis: true mean is greater than 98.54167
## 90 percent confidence interval:
##  96.21024      Inf
## sample estimates:
## mean of x 
##  97.38519</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="PH.html#cb31-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb31-2"><a href="PH.html#cb31-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">0.8965</span></span>
<span id="cb31-3"><a href="PH.html#cb31-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb31-4"><a href="PH.html#cb31-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.1</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 0.8965 no es menor o igual a la significancia del 0.1, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Minería es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(t_0 \geq t_{1-\alpha,n-1}\)</span>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="PH.html#cb33-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb33-2"><a href="PH.html#cb33-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.1</span>, <span class="at">df =</span> <span class="dv">53</span>)</span>
<span id="cb33-3"><a href="PH.html#cb33-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 1.29773</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="PH.html#cb35-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb35-2"><a href="PH.html#cb35-2" tabindex="-1"></a>t0 <span class="ot">=</span> <span class="sc">-</span><span class="fl">1.2773</span></span>
<span id="cb35-3"><a href="PH.html#cb35-3" tabindex="-1"></a>t0 <span class="sc">&gt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El estadístico de prueba de -1.2773 no es mayor o igual al valor crítico de 1.2977, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Minería es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\mu_0 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="PH.html#cb37-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb37-2"><a href="PH.html#cb37-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> <span class="fl">96.21024</span></span>
<span id="cb37-3"><a href="PH.html#cb37-3" tabindex="-1"></a><span class="fl">98.54167</span> <span class="sc">&lt;</span> Limite_inferior</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((96.21024, \infty)\)</span> contiene al valor de <span class="math inline">\(\mu_0 = 98.54167\)</span>, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Minería es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
</ol>
<p>La prueba de hipótesis para el sector de industria es la siguiente.</p>
<ul>
<li><span class="math inline">\(\mu:\)</span> Media del Imacec de Industria.</li>
</ul>
<span class="math display">\[\begin{equation}
    \notag
    \begin{split}
        H_0: \mu = 98.54167\\
        H_1: \mu &gt; 98.54167
    \end{split}
\end{equation}\]</span>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="PH.html#cb39-1" tabindex="-1"></a><span class="co"># Industria</span></span>
<span id="cb39-2"><a href="PH.html#cb39-2" tabindex="-1"></a><span class="fu">t.test</span>( <span class="co"># Prueba de hipótesis para el estadístico con distribución t-student</span></span>
<span id="cb39-3"><a href="PH.html#cb39-3" tabindex="-1"></a>  <span class="at">x =</span> df<span class="sc">$</span>Industria, <span class="co"># Valores del Imacec de Industria</span></span>
<span id="cb39-4"><a href="PH.html#cb39-4" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="co"># Signo de desigualdad de la hipótesis alternativa</span></span>
<span id="cb39-5"><a href="PH.html#cb39-5" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fl">98.54167</span>, <span class="co"># Valor del Mu_0</span></span>
<span id="cb39-6"><a href="PH.html#cb39-6" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.9</span> <span class="co"># Confianza = 1 - alfa</span></span>
<span id="cb39-7"><a href="PH.html#cb39-7" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$Industria
## t = 1.3678, df = 53, p-value = 0.08857
## alternative hypothesis: true mean is greater than 98.54167
## 90 percent confidence interval:
##  98.60095      Inf
## sample estimates:
## mean of x 
##  99.69815</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="PH.html#cb41-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb41-2"><a href="PH.html#cb41-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">0.08857</span></span>
<span id="cb41-3"><a href="PH.html#cb41-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb41-4"><a href="PH.html#cb41-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.1</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 0.8965 menor o igual a la significancia del 0.1, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Industria es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(t_0 \geq t_{1-\alpha,n-1}\)</span>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="PH.html#cb43-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb43-2"><a href="PH.html#cb43-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.1</span>, <span class="at">df =</span> <span class="dv">53</span>)</span>
<span id="cb43-3"><a href="PH.html#cb43-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 1.29773</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="PH.html#cb45-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb45-2"><a href="PH.html#cb45-2" tabindex="-1"></a>t0 <span class="ot">=</span> <span class="fl">1.3678</span></span>
<span id="cb45-3"><a href="PH.html#cb45-3" tabindex="-1"></a>t0 <span class="sc">&gt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El estadístico de prueba de 1.3678 es mayor o igual al valor crítico de 1.2977, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Industria es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\mu_0 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="PH.html#cb47-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb47-2"><a href="PH.html#cb47-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> <span class="fl">98.6009</span></span>
<span id="cb47-3"><a href="PH.html#cb47-3" tabindex="-1"></a><span class="fl">98.54167</span> <span class="sc">&lt;</span> Limite_inferior</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((98.6009, \infty)\)</span> no contiene al valor de <span class="math inline">\(\mu_0 = 98.54167\)</span>, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el valor promedio del Imacec del sector de Industria es mayor a 98.54167. Considerando una confianza del 90%.</p></li>
</ol>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-68" class="exercise"><strong>Ejercicio 2.12  </strong></span>Utilizando la base de datos <a href="PH.html#Imacec2">Imacec</a>, establezca si hay suficiente evidencia estadística para afirmar que, el valor promedio del Imacec de cada sector durante el año 2022 es mayor 96.89167. Establezca las hipótesis, estadísticos y criterios de rechazo. Utilice una significancia del 7%. Además, asuma que las variables distribuyen normal y tienen varianza poblacional desconocida. Concluya.</p>
</div>
<div class="exercise">
<p><span id="exr:metano" class="exercise"><strong>Ejercicio 2.13  </strong></span>El control de emisión de residuos ha sido un tema que ha cobrado gran importancia en los últimos 20 años debido a los efectos del calentamiento global. Uno de los tantos residuos que contamina el aire es el Metano (CH4). Para estudiar este fenómeno haremos uso de la base <a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%202/metano.csv"><em>metano.csv</em></a>, la cual contiene los siguientes datos:</p>
<ul>
<li>Año: año en el que se realiza la medición de emisión de CH4.</li>
<li>Mes: mes del año en el que se realiza la medición de emisión de CH4.</li>
<li>CH4: concentración de CH4 (partes por miles de millones) en un muestra de aire.</li>
</ul>
<p>Establezca si hay suficiente evidencia estadística para afirmar lo siguiente:</p>
<ol style="list-style-type: decimal">
<li>La concentración promedio de metano es distinta a 1700 partes por miles de millones.</li>
<li>La concentración promedio de metano del año 2021 es superior a 1780 partes por miles de millones.</li>
<li>La concentración promedio de metano del periodo en el periodo de años 2019 - 2022 (inclusive) es inferior a 1750 partes por miles de millones.</li>
</ol>
<p>Establezca las hipótesis respectivas, estadísticos y criterios de rechazo, utilice una significancia del 7%. Asuma que las variables distribuyen normal y tienen varianza poblacional desconocida. Concluya.</p>
</div>
<div class="exercise">
<p><span id="exr:consumidor" class="exercise"><strong>Ejercicio 2.14  </strong></span>Utilizando la base de datos <a href="PH.html#ICC">ICC</a>, estudie si hay suficiente evidencia estadística para afirmar lo siguiente:</p>
<ol style="list-style-type: decimal">
<li>El promedio del ICC es distinto a 100 puntos.</li>
<li>El promedio del ICC en Francia es menor a 105 puntos.</li>
<li>El promedio del ICC en Alemania es mayor a 107 puntos.</li>
</ol>
<p>Establezca las hipótesis, estadísticos y criterios de rechazo. Utilice una significancia del 12%. Además, asuma que las variables distribuyen normal y tienen varianza poblacional desconocida. Concluya.</p>
</div>
</div>
</div>
<div id="prueba-de-hipotesis-diferencia-de-medias" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Prueba de hipótesis para la diferencia de medias<a href="PH.html#prueba-de-hipotesis-diferencia-de-medias" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se continúa con el estudio de la inferencia estadística, específicamente para la diferencia entre dos medias poblacionales. Por ejemplo, quizá desee obtener una estimación por intervalo para la diferencia entre el salario inicial medio de la población de hombres y el salario inicial medio de la población de mujeres <span class="citation">(<a href="#ref-anderson">Anderson et al., 2008</a>, página 395)</span>. Para este tipo de pruebas, se requiere que las distribuciones poblacionales de las variables sean normales e independientes, lo cual, se asumirá en los enunciados de ejemplos y/o ejercicios según corresponda.</p>
<div id="prueba-de-hipotesis-diferencia-de-medias-varianzas-conocidas" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Varianzas poblacionales conocidas<a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-conocidas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El primero de los tres casos corresponde al de varianzas poblacionales conocidas. La tabla <a href="PH.html#tab:dosmedias1">2.6</a> da cuenta del estadístico de prueba asociado las respectivas hipótesis, además de los criterios asociados al valor crítico correspondiente.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dosmedias1">Tabla 2.6: </span>Método del valor crítico para la prueba de diferencia de medias con varianzas poblacionales conocidas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: \mu_X - \mu_Y = \delta_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(Z_0 = \displaystyle\frac{\bar{x} - \bar{y} - \delta_0}{\sqrt{\sigma^2_X/n_X + \sigma^2_Y/n_Y}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \neq \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|Z_0| \geq Z_{1-\alpha/2}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \gt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \geq Z_{1-\alpha}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \lt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \leq Z_{\alpha}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-69" class="example"><strong>Ejemplo 2.5  </strong></span>En dos ciudades se llevó acabo una encuesta sobre el costo de la vida, en relación al gasto promedio en alimentación en familias constituidas por cuatro personas. De cada ciudad se seleccionó aleatoriamente una muestra de 20 familias y se observaron sus gastos semanales en alimentación. Las medias muestrales y desviaciones estándar poblacionales fueron las siguientes:</p>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
\bar{x} = 135, &amp; \text{ } \sigma_X = 15\\
\bar{y} = 122, &amp; \text{ } \sigma_Y = 10
\end{split}
\end{equation}\]</span>
<p>Si se supone que se muestrearon dos poblaciones independientes con distribución normal cada una, analizar si existe una diferencia real entre ambas medias. Considere una confianza del 95%.</p>
<p>Las hipótesis a plantear son las siguientes.</p>
<ul>
<li><span class="math inline">\(\mu_X:\)</span> gasto medio semanal en alimentación en la ciudad X.</li>
<li><span class="math inline">\(\mu_Y:\)</span> gasto medio semanal en alimentación en la ciudad Y.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
  \begin{split}
    H_0&amp;: \mu_{X} - \mu_{Y} = 0\\
    H_1&amp;: \mu_{X} - \mu_{Y} \neq 0\\
  \end{split}
\end{equation}\]</span>
<p>Al igual que en la prueba para una media cuando se conoce la varianza poblacional, esta prueba no tiene una implementación directa en R, por lo que construiremos manualmente los métodos de rechazo.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="PH.html#cb49-1" tabindex="-1"></a>x.barra <span class="ot">=</span> <span class="dv">135</span></span>
<span id="cb49-2"><a href="PH.html#cb49-2" tabindex="-1"></a>y.barra <span class="ot">=</span> <span class="dv">122</span></span>
<span id="cb49-3"><a href="PH.html#cb49-3" tabindex="-1"></a>sigma.x <span class="ot">=</span> <span class="dv">15</span></span>
<span id="cb49-4"><a href="PH.html#cb49-4" tabindex="-1"></a>sigma.y <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb49-5"><a href="PH.html#cb49-5" tabindex="-1"></a>nx <span class="ot">=</span> <span class="dv">20</span></span>
<span id="cb49-6"><a href="PH.html#cb49-6" tabindex="-1"></a>ny <span class="ot">=</span> <span class="dv">20</span></span>
<span id="cb49-7"><a href="PH.html#cb49-7" tabindex="-1"></a>alfa <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb49-8"><a href="PH.html#cb49-8" tabindex="-1"></a>delta0 <span class="ot">=</span> <span class="dv">0</span></span></code></pre></div>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="PH.html#cb50-1" tabindex="-1"></a><span class="co"># Cálculo del estadístico de prueba</span></span>
<span id="cb50-2"><a href="PH.html#cb50-2" tabindex="-1"></a>z0 <span class="ot">=</span> (x.barra <span class="sc">-</span> y.barra <span class="sc">-</span> delta0)<span class="sc">/</span><span class="fu">sqrt</span>(sigma.x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>nx<span class="sc">+</span>sigma.y<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>ny)</span>
<span id="cb50-3"><a href="PH.html#cb50-3" tabindex="-1"></a>z0</span></code></pre></div>
<pre><code>## [1] 3.224903</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="PH.html#cb52-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb52-2"><a href="PH.html#cb52-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="dv">2-2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(z0))</span>
<span id="cb52-3"><a href="PH.html#cb52-3" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 0.001260153</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="PH.html#cb54-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb54-2"><a href="PH.html#cb54-2" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> alfa</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 0.0012 es menor o igual a la significancia del 0.05, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que existe diferencia entre los gastos de alimentación promedio entre las familias de ambas ciudades. Considerando una confianza del 95%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(|Z_0| \geq Z_{1-\alpha/2}\)</span>.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="PH.html#cb56-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb56-2"><a href="PH.html#cb56-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alfa<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb56-3"><a href="PH.html#cb56-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="PH.html#cb58-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb58-2"><a href="PH.html#cb58-2" tabindex="-1"></a><span class="fu">abs</span>(z0) <span class="sc">&gt;=</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alfa<span class="sc">/</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El valor absoluto del estadístico de prueba de 3.2249 es mayor o igual al valor crítico de 1.9599, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que existe diferencia entre los gastos de alimentación promedio entre las familias de ambas ciudades. Considerando una confianza del 95%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\delta_0 \notin\)</span> IC.</p>
<p>El intervalo de confianza a construir es:</p>
<span class="math display">\[\begin{equation}
  \notag
  \left(\bar{x} - \bar{y} \pm Z_{1-\alpha/2}\sqrt{\frac{\sigma_X^2}{n_X} + \frac{\sigma_Y^2}{n_Y}}\right)
\end{equation}\]</span>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="PH.html#cb60-1" tabindex="-1"></a><span class="co"># Cálculo de los límites del intervalo de confianza</span></span>
<span id="cb60-2"><a href="PH.html#cb60-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> x.barra <span class="sc">-</span> y.barra <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alfa<span class="sc">/</span><span class="dv">2</span>)<span class="sc">*</span><span class="fu">sqrt</span>(sigma.x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>nx <span class="sc">+</span> sigma.y<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>ny)</span>
<span id="cb60-3"><a href="PH.html#cb60-3" tabindex="-1"></a>Limite_superior <span class="ot">=</span> x.barra <span class="sc">-</span> y.barra <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alfa<span class="sc">/</span><span class="dv">2</span>)<span class="sc">*</span><span class="fu">sqrt</span>(sigma.x<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>nx <span class="sc">+</span> sigma.y<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>ny)</span>
<span id="cb60-4"><a href="PH.html#cb60-4" tabindex="-1"></a><span class="fu">c</span>(Limite_inferior, Limite_superior)</span></code></pre></div>
<pre><code>## [1]  5.099133 20.900867</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="PH.html#cb62-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb62-2"><a href="PH.html#cb62-2" tabindex="-1"></a><span class="dv">0</span> <span class="sc">&lt;</span> Limite_inferior <span class="sc">|</span> <span class="dv">0</span> <span class="sc">&gt;</span> Limite_superior</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((5.0991, 20.9008)\)</span> no contiene al valor de <span class="math inline">\(\delta_0 = 0\)</span>, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que existe diferencia entre los gastos de alimentación promedio entre las familias de ambas ciudades. Considerando una confianza del 95%.</p></li>
</ol>
</div>
</div>
<div class="exercise">
<p><span id="exr:cuotas" class="exercise"><strong>Ejercicio 2.15  </strong></span>La base <a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2023-1/control%2Bcuotas.csv"><em>control+cuotas.csv</em></a> contiene datos de los valores cuota de los primeros tres meses del año 2022 de las AFP Plan Vital y Provida, específicamente de un fondo A de un APV.</p>
<p>Se está interesado en saber si, la media de los valores cuota de Plan Vital supera al de Provida por más de 30000 pesos. Considere una confianza del 99%. Plantee y pruebe una hipótesis para la diferencia de medias, considerando <span class="math inline">\(\sigma^2_{\text{Provida}} = 1165833\)</span> y <span class="math inline">\(\sigma^2_{\text{Plan Vital}} = 3393141\)</span>. Utilice todos los métodos de rechazo.</p>
</div>
</div>
<div id="prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-iguales" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Varianzas poblacionales desconocidas e iguales<a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-iguales" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para el segundo caso, las varianzas poblacionales son desconocidas, sin embargo, los valores de estas varianzas poblacionales pueden ser iguales o distintos. La tabla <a href="PH.html#tab:dosmedias2">2.7</a> refleja el estadístico de prueba y los criterios de rechazo asociados al método del valor crítico, para el caso en que los valores de las varianzas poblacionaes desconocidas son iguales.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dosmedias2">Tabla 2.7: </span>Método del valor crítico para la prueba de diferencia de medias con varianzas poblacionales desconocidas e iguales
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: \mu_X - \mu_Y = \delta_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(t_0 = \displaystyle\frac{\bar{x} - \bar{y} - \delta_0}{S_p\sqrt{1/n_X + 1/n_Y}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \neq \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|t_0| \geq t_{1-\alpha/2,k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \gt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \geq t_{1-\alpha,k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \lt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \leq t_{\alpha,k}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>Donde los valores de <span class="math inline">\(k\)</span> y <span class="math inline">\(S_p\)</span> son los siguientes.</p>
<span class="math display">\[\begin{equation}
\notag
k = n_X + n_Y-2
\end{equation}\]</span>
<span class="math display">\[\begin{equation}
\notag
S_p^2 = \frac{(n_X-1)S_X^2 + (n_Y-1)S_Y^2}{n_X+n_Y-2}
\end{equation}\]</span>
<div class="blackbox">
<div class="example">
<p><span id="exm:consumidor" class="example"><strong>Ejemplo 2.6  </strong></span>Considere la base de datos <a href="PH.html#ICC">ICC</a>. Se está interesado en saber si el valor promedio del ICC en Alemania menos el de Francia es menor a 1.1. Elabore una prueba de hipótesis para analizar este interés con un 90% de confianza. Concluya utilizando el valor – p. Además, que las varianzas poblaciones son iguales.</p>
<ul>
<li><span class="math inline">\(\mu_X:\)</span> media del ICC de Alemania.</li>
<li><span class="math inline">\(\mu_Y:\)</span> media del ICC de Francia.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
  \begin{split}
    H_0&amp;: \mu_{X} - \mu_{Y} = 1.1\\
    H_1&amp;: \mu_{X} - \mu_{Y} &lt; 1.1\\
  \end{split}
\end{equation}\]</span>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="PH.html#cb64-1" tabindex="-1"></a><span class="co"># Cargue previamente la base guardándola con el nombre &quot;datos&quot;</span></span>
<span id="cb64-2"><a href="PH.html#cb64-2" tabindex="-1"></a>ICC_Alemania <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;DEU&quot;</span>] <span class="co"># Valores del ICC de Alemania</span></span>
<span id="cb64-3"><a href="PH.html#cb64-3" tabindex="-1"></a>ICC_Francia <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;FRA&quot;</span>] <span class="co"># Valores del ICC de Francia</span></span>
<span id="cb64-4"><a href="PH.html#cb64-4" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb64-5"><a href="PH.html#cb64-5" tabindex="-1"></a>  <span class="at">x =</span> ICC_Alemania,</span>
<span id="cb64-6"><a href="PH.html#cb64-6" tabindex="-1"></a>  <span class="at">y =</span> ICC_Francia,</span>
<span id="cb64-7"><a href="PH.html#cb64-7" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.9</span>, <span class="co"># Confianza</span></span>
<span id="cb64-8"><a href="PH.html#cb64-8" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>, <span class="co"># Signo según la hipótesis alternativa</span></span>
<span id="cb64-9"><a href="PH.html#cb64-9" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fl">1.1</span>, <span class="co"># Valor de delta0</span></span>
<span id="cb64-10"><a href="PH.html#cb64-10" tabindex="-1"></a>  <span class="at">var.equal =</span> T <span class="co"># Comando que indica que las varianzas son iguales</span></span>
<span id="cb64-11"><a href="PH.html#cb64-11" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  ICC_Alemania and ICC_Francia
## t = 0.10482, df = 132, p-value = 0.5417
## alternative hypothesis: true difference in means is less than 1.1
## 90 percent confidence interval:
##      -Inf 1.404981
## sample estimates:
## mean of x mean of y 
## 100.74328  99.62033</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="PH.html#cb66-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb66-2"><a href="PH.html#cb66-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">0.5417</span></span>
<span id="cb66-3"><a href="PH.html#cb66-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb66-4"><a href="PH.html#cb66-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.1</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 0.5417 no es menor o igual a la significancia del 0.1, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del ICC en Alemania menos el de Francia es menor a 1.1. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(t_0 \leq t_{\alpha,k}\)</span>.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="PH.html#cb68-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb68-2"><a href="PH.html#cb68-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.1</span>, <span class="at">df =</span> <span class="dv">132</span>)</span>
<span id="cb68-3"><a href="PH.html#cb68-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] -1.287998</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="PH.html#cb70-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb70-2"><a href="PH.html#cb70-2" tabindex="-1"></a>t0 <span class="ot">=</span> <span class="fl">0.10482</span></span>
<span id="cb70-3"><a href="PH.html#cb70-3" tabindex="-1"></a>t0 <span class="sc">&lt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El estadístico de prueba de 0.10482 no es menor o igual al valor crítico de -1.2879, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del ICC en Alemania menos el de Francia es menor a 1.1. Considerando una confianza del 90%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\delta_0 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="PH.html#cb72-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb72-2"><a href="PH.html#cb72-2" tabindex="-1"></a>Limite_superior <span class="ot">=</span> <span class="fl">1.4049</span></span>
<span id="cb72-3"><a href="PH.html#cb72-3" tabindex="-1"></a><span class="fl">1.1</span> <span class="sc">&gt;</span> Limite_superior</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((-\infty, 1.4049)\)</span> contiene al valor de <span class="math inline">\(\delta_0 = 1.1\)</span>, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de que el valor promedio del ICC en Alemania menos el de Francia es menor a 1.1. Considerando una confianza del 90%.</p></li>
</ol>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-70" class="exercise"><strong>Ejercicio 2.16  </strong></span>Utilizando la base de datos <a href="PH.html#ICC">ICC</a>, plantee y pruebe un hipótesis, para verificar si para el año 2019 existe una diferencia mayor a 1.2 entre el ICC promedio de Polonia e Italia, con una confianza del 93%. Utilice el método del intervalo de confianza. Además, asuma que las varianzas poblacionales son desconocidas e iguales.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-71" class="exercise"><strong>Ejercicio 2.17  </strong></span>Los desastres naturales pueden ocurrir en cualquier lugar y, cuando estos se dan lugares donde la población es densa, pueden afectar a diversos componentes de la sociedad, entre ellos la economía, ya que los daños pueden traducirse en pérdida o destrucción de bienes de capital, niveles de ahorro, incremento de precios, entre otros efectos.</p>
<p>Para estudiar este fenómeno, utilizaremos la base de datos <a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%202/terremotos.csv"><em>terremotos.csv</em></a>, la cual contiene datos sobre los terremotos ocurridos a nivel mundial entre los años 1900 y 2014. Las columnas de la base de datos son:</p>
<ul>
<li>Año: año de ocurrencia del terremoto.</li>
<li>Latitud: grados decimales de la coordenada de latitud (valores negativos para latitudes del sur).</li>
<li>Longitud: grados decimales de la coordenada de longitud (valores negativos para longitudes occidentales).</li>
<li>Profundidad: profundidad del evento en kilómetros.</li>
<li>Magnitud: magnitud del evento (la escala no es fija, ya que, a través de los años, la escala a cambiado según el método de medición. Sin embargo, todos las magnitudes son comparables, indicando que a mayor magnitud, mayor es la intensidad en movimiento/fuerza del terremoto).</li>
</ul>
<p>A continuación elabore las siguiente pruebas.</p>
<ol style="list-style-type: decimal">
<li><p>Establezca una prueba de hipótesis con un 93% de confianza para estudiar si, existe diferencia entre los promedios de las profundidades de los terremotos ocurridos en los años 1976 y 1986. Asuma varianzas poblacionales desconocidas e iguales.</p></li>
<li><p>Establezca una prueba de hipótesis con un 97% de confianza para estudiar si, el promedio las magnitudes de los terremotos en los años 1900 y 1922 es mayor al de los años 2010 y 2014, por más de 0.5 unidades de medida. Asuma varianzas poblacionales desconocidas e iguales.</p></li>
</ol>
</div>
</div>
<div id="prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-distintas" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Varianzas poblacionales desconocidas y distintas<a href="PH.html#prueba-de-hipotesis-diferencia-de-medias-varianzas-desconocidas-distintas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El último de los casos, las varianzas poblacionales son desconocidas y distintas. El detalle del estadístico de prueba y los criterios del método del valor crítico asociados se encuentran en la tabla <a href="PH.html#tab:dosmedias3">2.8</a>.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dosmedias3">Tabla 2.8: </span>Método del valor crítico para la prueba de diferencia de medias con varianzas poblacionales desconocidas y distintas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: \mu_X - \mu_Y = \delta_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(t_0 = \displaystyle\frac{\bar{x} - \bar{y} - \delta_0}{\sqrt{S^2_X/n_X + S^2_Y/n_Y}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \neq \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|t_0| \geq t_{1-\alpha/2,k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \gt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \geq t_{1-\alpha,k}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: \mu_X - \mu_Y \lt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(t_0 \leq t_{\alpha,k}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>dónde <span class="math inline">\(k\)</span> es el entero más cercano a</p>
<span class="math display">\[\begin{equation}
\notag
\frac{(S_X^2/n_X + S_Y^2/n_Y)^2}{(S_X^2/n_X)^2/(n_X-1) + (S_Y^2/n_Y)^2/(n_Y-1)}
\end{equation}\]</span>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-72" class="example"><strong>Ejemplo 2.7  </strong></span>Utilizando la base de datos del <a href="PH.html#ICC">ICC</a>, establecer una prueba de hipótesis para verificar si el ICC promedio de Italia es mayor al de Francia, con una significancia del 3%. Asumiendo que las varianzas poblacionales son desconocidas y distintas.</p>
<p>Las hipótesis a plantear son las siguientes.</p>
<ul>
<li><span class="math inline">\(\mu_X:\)</span> media del ICC de Italia</li>
<li><span class="math inline">\(\mu_Y:\)</span> media del ICC de Francia.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
  \begin{split}
    H_0&amp;: \mu_{X} - \mu_{Y} = 0\\
    H_1&amp;: \mu_{X} - \mu_{Y} &gt; 0\\
  \end{split}
\end{equation}\]</span>
<p>Luego, la prueba se ejecuta con el siguiente código.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="PH.html#cb74-1" tabindex="-1"></a><span class="co"># Cargue previamente la base guardándola con el nombre &quot;datos&quot;</span></span>
<span id="cb74-2"><a href="PH.html#cb74-2" tabindex="-1"></a>ICC_Italia <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;ITA&quot;</span>] <span class="co"># Valores del ICC de Italia</span></span>
<span id="cb74-3"><a href="PH.html#cb74-3" tabindex="-1"></a>ICC_Francia <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;FRA&quot;</span>] <span class="co"># Valores del ICC de Francia</span></span>
<span id="cb74-4"><a href="PH.html#cb74-4" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb74-5"><a href="PH.html#cb74-5" tabindex="-1"></a>  <span class="at">x =</span> ICC_Italia,</span>
<span id="cb74-6"><a href="PH.html#cb74-6" tabindex="-1"></a>  <span class="at">y =</span> ICC_Francia,</span>
<span id="cb74-7"><a href="PH.html#cb74-7" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.97</span>, <span class="co"># Confianza</span></span>
<span id="cb74-8"><a href="PH.html#cb74-8" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="co"># Signo según la hipótesis alternativa</span></span>
<span id="cb74-9"><a href="PH.html#cb74-9" tabindex="-1"></a>  <span class="at">mu =</span> <span class="dv">0</span>, <span class="co"># Valor de delta0</span></span>
<span id="cb74-10"><a href="PH.html#cb74-10" tabindex="-1"></a>  <span class="at">var.equal =</span> F <span class="co"># Comando que indica que las varianzas son distintas</span></span>
<span id="cb74-11"><a href="PH.html#cb74-11" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ICC_Italia and ICC_Francia
## t = 4.0794, df = 131.74, p-value = 3.886e-05
## alternative hypothesis: true difference in means is greater than 0
## 97 percent confidence interval:
##  0.4887855       Inf
## sample estimates:
## mean of x mean of y 
## 100.53403  99.62033</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="PH.html#cb76-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb76-2"><a href="PH.html#cb76-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">3.886e-05</span></span>
<span id="cb76-3"><a href="PH.html#cb76-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb76-4"><a href="PH.html#cb76-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.03</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 3.886e-05 es menor o igual a la significancia del 0.03, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el ICC promedio de Italia es mayor al de Francia. Considerando una confianza del 97%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(t_0 \geq t_{1-\alpha,k}\)</span>.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="PH.html#cb78-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb78-2"><a href="PH.html#cb78-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.03</span>, <span class="at">df =</span> <span class="dv">132</span>)</span>
<span id="cb78-3"><a href="PH.html#cb78-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 1.897095</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="PH.html#cb80-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb80-2"><a href="PH.html#cb80-2" tabindex="-1"></a>t0 <span class="ot">=</span> <span class="fl">4.0794</span></span>
<span id="cb80-3"><a href="PH.html#cb80-3" tabindex="-1"></a>t0 <span class="sc">&gt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El estadístico de prueba de 4.0794 es mayor o igual al valor crítico de 1.8970, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el ICC promedio de Italia es mayor al de Francia. Considerando una confianza del 97%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\delta_0 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="PH.html#cb82-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb82-2"><a href="PH.html#cb82-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> <span class="fl">0.4887</span></span>
<span id="cb82-3"><a href="PH.html#cb82-3" tabindex="-1"></a><span class="dv">0</span> <span class="sc">&lt;</span> Limite_inferior</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((0.4887,\infty)\)</span> no contiene al valor de <span class="math inline">\(\delta_0 = 0\)</span>, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que el ICC promedio de Italia es mayor al de Francia. Considerando una confianza del 97%.</p></li>
</ol>
</div>
</div>
<div class="exercise">
<p><span id="exr:energia" class="exercise"><strong>Ejercicio 2.18  </strong></span>La energía renovable es esencial para reducir las emisiones de carbono y mitigar el cambio climático. Además, la energía renovable mejora la salud pública, crea nuevos puestos de trabajo, garantiza la seguridad energética a través de la diversificación y estabiliza los precios de la energía.</p>
<p>La importancia de alejarse de los combustibles fósiles y acercarse a las fuentes renovables no puede subestimarse. Como tal, este conjunto de datos (<a href="https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2022-2/Estad%C3%ADstica%202/energia.csv"><em>energia.csv</em></a>) rastrea el crecimiento del sector renovable del Reino Unido desde 1990 hasta 2020. Las columnas de la base de datos son las siguientes:</p>
<ul>
<li>Ano: año de medición.</li>
<li>Renovables.Residuos: Energía procedente de fuentes renovables y de residuos.</li>
<li>Consumo.Total: Consumo total de energía de combustibles primarios y equivalentes.</li>
<li>Hidroelectrica: Consumo de energía producido por hidroeléctricas.</li>
<li>Viento.Olas: Consumo de energía producido por vientos, olas y mareas.</li>
<li>Solar Consumo de energía producido por paneles fotovoltaicos.</li>
<li>Geo: Consumo de energía producido por acuíferos geotérmicos.</li>
<li>Vertedero: Consumo de energía producido por gases de vertedero.</li>
<li>Gas: Consumo de energía producido por gases de aguas residuales.</li>
</ul>
<p>La unidad de energía utilizada en este conjunto de datos es la megatonelada equivalente de petróleo (mtep).</p>
<p>A continuación elabore las siguiente pruebas.</p>
<ol style="list-style-type: decimal">
<li><p>Elabore una prueba de hipótesis con una confianza del 97% para estudiar si, existe diferencia entre el promedio de energía consumida mediante gases de aguas residuales y la consumida mediante hidroeléctricas. Asuma que las varianzas poblacionales son desconocidas y distintas.</p></li>
<li><p>Elabore una prueba de hipótesis con una confianza del 98% para estudiar si, la diferencia del promedio de la energía consumida por gases de vertederos es mayor a la consumida por paneles fotovoltaicos. Asuma que las varianzas poblacionales son desconocidas y distintas.</p></li>
<li><p>Elabore un intervalo de confianza al 99% para estudiar si, el promedio del consumo total de energía durante el periodo 2004 - 2020 es menor al del periodo 1990 - 2003 por más de 40 unidades. Asuma que las varianzas poblacionales son desconocidas y distintas.</p></li>
</ol>
</div>
</div>
</div>
<div id="prueba-de-hipotesis-comparacion-varianzas" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Prueba de hipótesis para comparación de varianzas<a href="PH.html#prueba-de-hipotesis-comparacion-varianzas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se extiende el estudio a las varianzas poblacionales, con al finalidad de estableces si estas son iguales o distintas. Para ello, se requiere que las distribuciones poblacionales de las variables de estudios sean normales e independientes, lo cual, se asumirá en los enunciados de los ejemplos y/o ejercicios según corresponda.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:varianzas">Tabla 2.9: </span>Método del valor crítico para la prueba de comparación de varianzas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;background-color: white !important;" rowspan="4">
<span class="math inline">\(H_0: \sigma_X^2 = \sigma_Y^2\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;background-color: white !important;" rowspan="4">
<span class="math inline">\(f_0 = S_X^2/S_Y^2\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;background-color: white !important;" rowspan="2">
<span class="math inline">\(H_1: \sigma_X^2 \neq \sigma_Y^2\)</span>
</td>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(f_0 \geq f_{1-\alpha/2,n_X-1,n_Y-1} \vee\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(f_0 \leq f_{\alpha/2,n_X-1,n_Y-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(H_1: \sigma_X^2 \gt \sigma_Y^2\)</span>
</td>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(f_0 \geq f_{1-\alpha,n_X-1,n_Y-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(H_1: \sigma_X^2 \lt \sigma_Y^2\)</span>
</td>
<td style="text-align:left;background-color: white !important;">
<span class="math inline">\(f_0 \leq f_{\alpha,n_X-1,n_Y-1}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>Gracias a esta prueba, es posible determinar de antemano si las varianzas poblacionales son iguales o distintas asumiendo que son desconocidas, lo cual, permite elegir posteriormente que tipo de pruebas para la diferencia de medias se debe realizar.</p>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-73" class="example"><strong>Ejemplo 2.8  </strong></span>Utilizando la base de datos del <a href="PH.html#ICC">ICC</a>, establecer una prueba de hipótesis para verificar si el ICC promedio de España es distinto al de Polonia, con una significancia del 4%. Asumiendo muestras independientes.</p>
<p>En primer lugar se establece la prueba de hipótesis para la igualdad de varianzas.</p>
<ul>
<li><span class="math inline">\(\sigma^2_X:\)</span> varianza del ICC de España.</li>
<li><span class="math inline">\(\sigma^2_Y:\)</span> varianza del ICC de Polonia.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
  \begin{split}
    H_0&amp;: \sigma^2_{X} = \sigma^2_{Y}\\
    H_1&amp;: \sigma^2_{X} \neq \sigma^2_{Y}\\
  \end{split}
\end{equation}\]</span>
<p>El código para realizar esta prueba es el siguiente.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="PH.html#cb84-1" tabindex="-1"></a><span class="co"># Cargue previamente la base guardándola con el nombre &quot;datos&quot;</span></span>
<span id="cb84-2"><a href="PH.html#cb84-2" tabindex="-1"></a>ICC_Espana <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;ESP&quot;</span>] <span class="co"># Valores del ICC de España</span></span>
<span id="cb84-3"><a href="PH.html#cb84-3" tabindex="-1"></a>ICC_Polonia <span class="ot">=</span> datos<span class="sc">$</span>ICC[datos<span class="sc">$</span>Locacion <span class="sc">==</span> <span class="st">&quot;POL&quot;</span>] <span class="co"># Valores del ICC de Polonia</span></span>
<span id="cb84-4"><a href="PH.html#cb84-4" tabindex="-1"></a><span class="fu">var.test</span>(</span>
<span id="cb84-5"><a href="PH.html#cb84-5" tabindex="-1"></a>  <span class="at">x =</span> ICC_Espana,</span>
<span id="cb84-6"><a href="PH.html#cb84-6" tabindex="-1"></a>  <span class="at">y =</span> ICC_Polonia,</span>
<span id="cb84-7"><a href="PH.html#cb84-7" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co"># Tipo de hipótesis alternativa</span></span>
<span id="cb84-8"><a href="PH.html#cb84-8" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.96</span> <span class="co"># Confianza</span></span>
<span id="cb84-9"><a href="PH.html#cb84-9" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  ICC_Espana and ICC_Polonia
## F = 3.5354, num df = 66, denom df = 66, p-value = 7.241e-07
## alternative hypothesis: true ratio of variances is not equal to 1
## 96 percent confidence interval:
##  2.122496 5.888850
## sample estimates:
## ratio of variances 
##           3.535401</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="PH.html#cb86-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb86-2"><a href="PH.html#cb86-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">7.241e-07</span></span>
<span id="cb86-3"><a href="PH.html#cb86-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb86-4"><a href="PH.html#cb86-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.04</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 3.886e-05 es menor o igual a la significancia del 0.03, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que las varianzas poblacionales son desconocidas y distintas. Considerando una confianza del 96%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(f_0 \geq f_{1-\alpha/2,n_X-1,n_Y-1} \vee f_0 \leq f_{\alpha/2,n_X-1,n_Y-1}\)</span>.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="PH.html#cb88-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb88-2"><a href="PH.html#cb88-2" tabindex="-1"></a>valor_critico_1 <span class="ot">=</span> <span class="fu">qf</span>(<span class="dv">1</span><span class="fl">-0.04</span><span class="sc">/</span><span class="dv">2</span>, <span class="at">df1 =</span> <span class="dv">66</span>, <span class="at">df2 =</span> <span class="dv">66</span>)</span>
<span id="cb88-3"><a href="PH.html#cb88-3" tabindex="-1"></a>valor_critico_2 <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.04</span><span class="sc">/</span><span class="dv">2</span>, <span class="at">df1 =</span> <span class="dv">66</span>, <span class="at">df2 =</span> <span class="dv">66</span>)</span>
<span id="cb88-4"><a href="PH.html#cb88-4" tabindex="-1"></a><span class="fu">c</span>(valor_critico_1, valor_critico_2)</span></code></pre></div>
<pre><code>## [1] 1.6656807 0.6003551</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="PH.html#cb90-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb90-2"><a href="PH.html#cb90-2" tabindex="-1"></a>f0 <span class="ot">=</span> <span class="fl">3.5354</span></span>
<span id="cb90-3"><a href="PH.html#cb90-3" tabindex="-1"></a>f0 <span class="sc">&gt;=</span> valor_critico_1 <span class="sc">|</span> f0 <span class="sc">&lt;=</span> valor_critico_2</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El estadístico de prueba de 3.5354 es mayor o igual, o, menor o igual a los valores críticos de 1.6656 y 0.6003 respectivamente, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que las varianzas poblacionales son desconocidas y distintas. Considerando una confianza del 96%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(1 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="PH.html#cb92-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb92-2"><a href="PH.html#cb92-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> <span class="fl">2.122496</span></span>
<span id="cb92-3"><a href="PH.html#cb92-3" tabindex="-1"></a>Limite_superior <span class="ot">=</span> <span class="fl">5.888850</span></span>
<span id="cb92-4"><a href="PH.html#cb92-4" tabindex="-1"></a><span class="dv">1</span> <span class="sc">&lt;</span> Limite_inferior <span class="sc">|</span> <span class="dv">1</span> <span class="sc">&gt;</span> Limite_superior</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((2.1224, 5.8888)\)</span> no contiene al 1, por lo cual, existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, existe suficiente evidencia para apoyar la afirmación de que las varianzas poblacionales son desconocidas y distintas. Considerando una confianza del 96%.</p></li>
</ol>
<p>Luego, las hipótesis para la diferencia de medias son las siguientes.</p>
<ul>
<li><span class="math inline">\(\mu_X:\)</span> media del ICC de España.</li>
<li><span class="math inline">\(\mu_Y:\)</span> media del ICC de Polonia.</li>
</ul>
<span class="math display">\[\begin{equation}
  \begin{split}
    H_0&amp;: \mu_{\text{X}} - \mu_{\text{Y}} = 0\\
    H_1&amp;: \mu_{\text{X}} - \mu_{\text{Y}} \neq 0\\
  \end{split}
\end{equation}\]</span>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="PH.html#cb94-1" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb94-2"><a href="PH.html#cb94-2" tabindex="-1"></a>  <span class="at">x =</span> ICC_Espana,</span>
<span id="cb94-3"><a href="PH.html#cb94-3" tabindex="-1"></a>  <span class="at">y =</span> ICC_Polonia,</span>
<span id="cb94-4"><a href="PH.html#cb94-4" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co"># Tipo de hipótesis alternativa</span></span>
<span id="cb94-5"><a href="PH.html#cb94-5" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.96</span>, <span class="co"># Confianza</span></span>
<span id="cb94-6"><a href="PH.html#cb94-6" tabindex="-1"></a>  <span class="at">mu =</span> <span class="dv">0</span>, <span class="co"># delta0</span></span>
<span id="cb94-7"><a href="PH.html#cb94-7" tabindex="-1"></a>  <span class="at">var.equal =</span> F <span class="co"># Varianzas poblacionales distintas</span></span>
<span id="cb94-8"><a href="PH.html#cb94-8" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ICC_Espana and ICC_Polonia
## t = -1.4661, df = 100.57, p-value = 0.1458
## alternative hypothesis: true difference in means is not equal to 0
## 96 percent confidence interval:
##  -1.4752851  0.2556696
## sample estimates:
## mean of x mean of y 
##  100.3420  100.9518</code></pre>
<ol style="list-style-type: decimal">
<li><p><strong>Método del valor-p</strong></p>
<p>Verificación del criterio de rechazo: Valor-p <span class="math inline">\(\leq \alpha\)</span>.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="PH.html#cb96-1" tabindex="-1"></a><span class="co"># Cálculo del valor-p</span></span>
<span id="cb96-2"><a href="PH.html#cb96-2" tabindex="-1"></a>valor_p <span class="ot">=</span> <span class="fl">0.1458</span></span>
<span id="cb96-3"><a href="PH.html#cb96-3" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb96-4"><a href="PH.html#cb96-4" tabindex="-1"></a>valor_p <span class="sc">&lt;=</span> <span class="fl">0.04</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor-p</strong>: El valor-p de 0.1458 no es menor o igual a la significancia del 0.04, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de el ICC promedio de España es distinto al de Polonia. Considerando una confianza del 96%.</p></li>
<li><p><strong>Método del valor crítico</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(|t_0| \geq t_{1-\alpha/2,k}\)</span>.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="PH.html#cb98-1" tabindex="-1"></a><span class="co"># Cálculo del valor crítico</span></span>
<span id="cb98-2"><a href="PH.html#cb98-2" tabindex="-1"></a>valor_critico <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="fl">-0.04</span><span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> <span class="dv">101</span>)</span>
<span id="cb98-3"><a href="PH.html#cb98-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 2.080612</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="PH.html#cb100-1" tabindex="-1"></a><span class="co"># Verificación el criterio</span></span>
<span id="cb100-2"><a href="PH.html#cb100-2" tabindex="-1"></a>t0 <span class="ot">=</span> <span class="sc">-</span><span class="fl">1.4661</span></span>
<span id="cb100-3"><a href="PH.html#cb100-3" tabindex="-1"></a><span class="fu">abs</span>(t0) <span class="sc">&gt;=</span> valor_critico</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del valor crítico</strong>: El valor absoluto del estadístico de prueba de 1.4661 no es mayor o igual al valor crítico de 2.0806, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de el ICC promedio de España es distinto al de Polonia. Considerando una confianza del 96%.</p></li>
<li><p><strong>Método del intervalo de confianza</strong></p>
<p>Verificación del criterio de rechazo: <span class="math inline">\(\delta_0 \notin\)</span> IC.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="PH.html#cb102-1" tabindex="-1"></a><span class="co"># Verificación del criterio</span></span>
<span id="cb102-2"><a href="PH.html#cb102-2" tabindex="-1"></a>Limite_inferior <span class="ot">=</span> <span class="sc">-</span><span class="fl">1.4752</span></span>
<span id="cb102-3"><a href="PH.html#cb102-3" tabindex="-1"></a>Limite_superior <span class="ot">=</span> <span class="fl">0.2556</span></span>
<span id="cb102-4"><a href="PH.html#cb102-4" tabindex="-1"></a><span class="dv">0</span> <span class="sc">&lt;</span> Limite_inferior <span class="sc">|</span> <span class="dv">0</span> <span class="sc">&gt;</span> Limite_superior</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>Interpretación utilizando el método del intervalo de confianza</strong>: El intervalo de confianza <span class="math inline">\((-1.4752, 0.25568)\)</span> contiene al valor de <span class="math inline">\(\delta_0 = 0\)</span>, por lo cual, no existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, no existe suficiente evidencia para apoyar la afirmación de el ICC promedio de España es distinto al de Polonia. Considerando una confianza del 96%.</p></li>
</ol>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-74" class="exercise"><strong>Ejercicio 2.19  </strong></span>La contaminación del aire representa un importante riesgo medioambiental para la salud. Mediante la disminución de los niveles de contaminación del aire los países pueden reducir la carga de morbilidad derivada de accidentes cerebrovasculares, cánceres de pulmón y neumopatías crónicas y agudas, entre ellas el asma. Cuanto más bajos sean los niveles de contaminación del aire mejor será la salud cardiovascular y respiratoria de la población, tanto a largo como a corto plazo.</p>
<p>Por lo anteriormente mencionado, utilizaremos una base de datos propia de R (<em>airquality</em>) para estudiar la calidad del aire. Esta base de datos contiene mediciones diarias de la calidad del aire en Nueva York, de mayo a septiembre de 1973. Las columnas son las siguientes:</p>
<ul>
<li>Ozone: Ozono medio en partes por billón.</li>
<li>Solar.R: Radiación solar en Langleys (unidad de medida de la radiación solar).</li>
<li>Wind: Velocidad promedio del viento en millas por hora.</li>
<li>Temp: Temperatura máxima diaria en grados Fahrenheit.</li>
<li>Month: Mes de medición.</li>
<li>Day: Día de medición.</li>
</ul>
<p>Elimine los datos faltantes de la base de datos con el comando <code>na.omit()</code>. A continuación:</p>
<p>Plantee y pruebe una hipótesis para estudiar la diferencia entre el promedio de concentración de Ozono en los primeros 15 días del mes y el promedio de concentración de Ozono en el resto de los días del mes. Utilice una confianza del 92%. Interprete los intervalos de confianza y valores - p de todas las pruebas a utilizar.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-75" class="exercise"><strong>Ejercicio 2.20  </strong></span>La base de datos <em>CO2</em> (incroporrada en R) contiene datos de un experimento sobre la tolerancia al frío de la especie de pasto Echinochloa crus-galli. Las columnas son las siguientes:</p>
<ul>
<li>Plant: Identificador del tipo de planta.</li>
<li>Type: Lugar de origen de la planta.</li>
<li>Treatment: indica si la planta fue refrigerada (chilled) o no (nonchilled).</li>
<li>conc: Concentraciones ambientales de dióxido de carbono (mL/L).</li>
<li>uptake: Tasas de absorción de dióxido de carbono (<span class="math inline">\(umol/m^2\)</span> seg) de las plantas.</li>
</ul>
<p>A continuación, plantee y pruebe una hipótesis para estudiar si, la diferencia entre el promedio de la tasa de absorción de dióxido de carbono de las dos zonas medidas está a favor de Mississippi. Utilice una confianza del 96%. Haga uso de todos los métodos de rechazo. Interprete.</p>
</div>
</div>
<div id="prueba-de-hipotesis-diferencia-proporciones" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Prueba de hipótesis para la diferencia de proporciones<a href="PH.html#prueba-de-hipotesis-diferencia-proporciones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Después de presentar métodos para comparar las medidas de dos poblaciones diferentes, ahora se presta atención a la comparación de dos proporciones de población. Las proporciones se plantear de la siguiente manera <span class="citation">(<a href="#ref-Devore">Devore, 2008</a>, página 353)</span>.</p>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
p_1 &amp;= \text{la proporción de éxitos en la población 1}\\
p_2 &amp;= \text{la proporción de éxitos en la población 2}\\
\end{split}
\end{equation}\]</span>
<p>La prueba de hipótesis que permite comparar la diferencia entre estás proporciones, asumiendo que las distribuciones poblacionales de las variables son binomiales e independientes, es la siguiente</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:proporciones">Tabla 2.10: </span>Criterios de rechazo para la prueba de diferencia de proporciones
</caption>
<thead>
<tr>
<th style="text-align:left;">
Hipótesis nula
</th>
<th style="text-align:left;">
Estadístico de prueba
</th>
<th style="text-align:left;">
Hipótesis alternativa
</th>
<th style="text-align:left;">
Criterio de rechazo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(H_0: p_X - p_Y = \delta_0\)</span>
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
<span class="math inline">\(Z_0 = \displaystyle\frac{\widehat{p}_X-\widehat{p}_Y-\delta_0}{\sqrt{\widehat{p}\widehat{q}\left( \frac{1}{n_X} + \frac{1}{n_Y} \right)}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(H_1: p_X - p_Y \neq \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(|Z_0| \geq Z_{1-\alpha/2}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: p_X - p_Y \gt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \geq Z_{1-\alpha}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_1: p_X - p_Y \lt \delta_0\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Z_0 \leq Z_{\alpha}\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>donde</p>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
\widehat{p} &amp;= \frac{n_X\widehat{p}_X}{n_X+n_Y} + \frac{n_Y\widehat{p}_Y}{n_X+n_Y}\\
\widehat{q} &amp; = 1 - \widehat{p}
\end{split}
\end{equation}\]</span>
<p>Existen otros estadísticos de prueba que se pueden elaborar para este tipo de hipótesis, en particular el que usa R es el estadístico <span class="math inline">\(\chi^2\)</span>. Este estadístico requiere que los datos estén dispuestos en una tabla, tal como se muestra a continuación.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:chi2">Tabla 2.11: </span>Tabla de contingencia en la prueba de hipótesis para la diferencia de proporciones
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Grupo 1
</th>
<th style="text-align:left;">
Grupo 2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Éxitos
</td>
<td style="text-align:left;">
<span class="math inline">\(O_1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(O_2\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Fracasos
</td>
<td style="text-align:left;">
<span class="math inline">\(O_3\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(O_4\)</span>
</td>
</tr>
</tbody>
</table>
</div>
<p>El estadístico en cuestión es el siguiente.</p>
<span class="math display">\[\begin{equation}
\notag
\chi^2_0 = \sum_{i=1}^n\frac{(O_i-E_i)^2}{E_i}
\end{equation}\]</span>
<p>Donde <span class="math inline">\(E_i\)</span> y <span class="math inline">\(O_i\)</span> corresponden a la frecuencia esperada y observada en cada celda respectivamente. Las frecuencias esperadas se calculan como el producto de las frecuencias marginales, divido por el total de observaciones. Cabe mencionar que, R solo tiene la capacidad de ejecutar esta prueba cuando <span class="math inline">\(\delta_0 = 0\)</span>, el cual, es el caso en el que nos concentraremos.</p>
<p>Los supuestos asociados a esta prueba de hipótesis se asumirán para los enunciados de los ejemplos y/o ejercicios según corresponda.</p>
<div class="blackbox">
<div class="example">
<p><span id="exm:unlabeled-div-76" class="example"><strong>Ejemplo 2.9  </strong></span>Se pretende comparar si existe diferencias en la eficacia de un nuevo fármaco, medido como proporción, entre hombres y mujeres. Los datos se aprecian en la siguiente tabla.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Hombre
</th>
<th style="text-align:center;">
Mujer
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Sí
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
No
</td>
<td style="text-align:center;">
120
</td>
<td style="text-align:center;">
110
</td>
</tr>
</tbody>
</table>
</div>
<p>La prueba de hipótesis a plantear, considerando un 95% de confianza, es la siguiente.</p>
<ul>
<li><span class="math inline">\(p_X:\)</span> proporción de hombres para los cuales le medicamento presentó eficacia.</li>
<li><span class="math inline">\(p_Y:\)</span> proporción de mujeres para los cuales le medicamento presentó eficacia.</li>
</ul>
<span class="math display">\[\begin{equation}
\notag
\begin{split}
H_0&amp;: p_X - p_Y = 0\\
H_1&amp;: p_X - p_Y \neq 0\\
\end{split}
\end{equation}\]</span>
<p>El comando en R para probar está hipótesis es:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="PH.html#cb104-1" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb104-2"><a href="PH.html#cb104-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">50</span>), <span class="co"># Vector que contenga las frecuencias de los éxitos</span></span>
<span id="cb104-3"><a href="PH.html#cb104-3" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">160</span>), <span class="co"># Vector que contenga los totales por grupo</span></span>
<span id="cb104-4"><a href="PH.html#cb104-4" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co"># Tipo de hipótesis alternativa</span></span>
<span id="cb104-5"><a href="PH.html#cb104-5" tabindex="-1"></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span>, <span class="co"># Confianza</span></span>
<span id="cb104-6"><a href="PH.html#cb104-6" tabindex="-1"></a>  <span class="at">correct =</span> F <span class="co"># T en caso de que el número de éxitos o fracasos sea menor a 5 (Corrección de Yates)</span></span>
<span id="cb104-7"><a href="PH.html#cb104-7" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity correction
## 
## data:  c(20, 50) out of c(140, 160)
## X-squared = 12.012, df = 1, p-value = 0.0005286
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.26193633 -0.07734938
## sample estimates:
##    prop 1    prop 2 
## 0.1428571 0.3125000</code></pre>
<p>Como se observa en la última línea de la salida del programa, la proporción de eficacia del fármaco en los hombres es del 14.28% y del 31.25% en las mujeres.</p>
<p>Al observar el valor-p (0.0005286), nos damos cuenta de que este es menor a la significancia (0.05). Además, el valor de <span class="math inline">\(\delta_0 = 0\)</span> no está contenido por intervalo de confianza (-0.26193633, -0.07734938), por lo que, existe suficiente evidencia estadística para rechazar <span class="math inline">\(H_0\)</span>, es decir, existe suficiente evidencia estadística apoyar la afirmación de que existe diferencia entre hombres y mujeres respecto a la eficacia del fármaco.</p>
</div>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-77" class="exercise"><strong>Ejercicio 2.21  </strong></span>Suponga que se quiere comparar la proporción de hogares que tienen una cuenta bancaria en dos países, A y B. En el país A, de una muestra aleatoria de 500 hogares, 400 tienen una cuenta bancaria, mientras que en el país B, de una muestra aleatoria de 800 hogares, 600 tienen una cuenta bancaria. Realice un análisis de la diferencia de proporciones, y determine si hay evidencia de que la proporción de hogares con cuenta bancaria es significativamente diferente entre los dos países.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-78" class="exercise"><strong>Ejercicio 2.22  </strong></span>Suponga que se quiere comparar la proporción de empresas que ofrecen seguro de salud a sus empleados entre dos sectores económicos, manufactura y servicios. En el sector manufacturero, de una muestra aleatoria de 300 empresas, 225 ofrecen seguro de salud a sus empleados, mientras que en el sector de servicios, de una muestra aleatoria de 400 empresas, 300 ofrecen seguro de salud a sus empleados. Realice un análisis de la diferencia de proporciones, y determine si hay evidencia de que la proporción de empresas que ofrecen seguro de salud es significativamente diferente entre los dos sectores.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-79" class="exercise"><strong>Ejercicio 2.23  </strong></span>Suponga que se quiere comparar la proporción de trabajadores con contratos temporales entre dos empresas, A y B. En la empresa A, de una muestra aleatoria de 400 trabajadores, 120 tienen contratos temporales, mientras que en la empresa B, de una muestra aleatoria de 500 trabajadores, 150 tienen contratos temporales. Realice un análisis de la diferencia de proporciones, y determine si hay evidencia de que la proporción de trabajadores con contratos temporales es significativamente mayor en la empresa A.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-80" class="exercise"><strong>Ejercicio 2.24  </strong></span>Suponga que se quiere comparar la proporción de clientes que compran un producto en dos tiendas, A y B. En la tienda A, de una muestra aleatoria de 600 clientes, 200 compran el producto, mientras que en la tienda B, de una muestra aleatoria de 800 clientes, 240 compran el producto. Realiza un análisis de la diferencia de proporciones, y determina si hay evidencia de que la proporción de clientes que compran el producto es significativamente menor en la tienda A.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-81" class="exercise"><strong>Ejercicio 2.25  </strong></span>Un estudio analizó la cantidad de personas que reciclan y, que a su vez, hacen uso de un servicio privado o público para la recolección de basura (incluye la recolección de reciclaje). Los datos registrados se reflejan en la siguiente tabla.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Reciclan
</th>
<th style="text-align:center;">
No reciclan
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Servicio privado
</td>
<td style="text-align:center;">
128
</td>
<td style="text-align:center;">
234
</td>
</tr>
<tr>
<td style="text-align:left;">
Servicio público
</td>
<td style="text-align:center;">
340
</td>
<td style="text-align:center;">
260
</td>
</tr>
</tbody>
</table>
</div>
<p>Plantee una prueba de hipótesis para estudiar si, la proporción de personas que reciclan qué usan el servicio público es menor a la proporción de personas que no reciclan qué uso del mismo tipo de servicio. Utilice una confianza del 97.9%. Concluya utilizando el método del valor-p. </p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-82" class="exercise"><strong>Ejercicio 2.26  </strong></span>La Encuesta de Caracterización Socioeconómica Nacional, Casen, es realizada por el Ministerio de Desarrollo Social y Familia con el objetivo de disponer de información que permita:</p>
<ul>
<li><p>Conocer periódicamente la situación de los hogares y de la población, especialmente de aquella en situación de pobreza y de aquellos grupos definidos como prioritarios por la política social, con relación a aspectos demográficos, de educación, salud, vivienda, trabajo e ingresos. En particular, estimar la magnitud de la pobreza y la distribución del ingreso; identificar carencias y demandas de la población en las áreas señaladas; y evaluar las distintas brechas que separan a los diferentes segmentos sociales y ámbitos territoriales.</p></li>
<li><p>Evaluar el impacto de la política social: estimar la cobertura, la focalización y la distribución del gasto fiscal de los principales programas sociales de alcance nacional entre los hogares, según su nivel de ingreso, para evaluar el impacto de este gasto en el ingreso de los hogares y en la distribución del mismo.
Su objeto de estudio son los hogares que habitan las viviendas particulares ocupadas que se ubican en el territorio nacional, exceptuando algunas comunas y partes de comunas definidas por el INE como áreas especiales, así como las personas que forman parte de esos hogares.</p></li>
</ul>
<p>La siguiente tabla, da cuenta de la cantidad de hombres y mujeres (jefes de familia) según su nivel educacional, de una muestra determinada.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Hombres
</th>
<th style="text-align:center;">
Mujeres
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Universitario completo
</td>
<td style="text-align:center;">
220
</td>
<td style="text-align:center;">
3201
</td>
</tr>
<tr>
<td style="text-align:left;">
Escolar completo
</td>
<td style="text-align:center;">
7141
</td>
<td style="text-align:center;">
4789
</td>
</tr>
<tr>
<td style="text-align:left;">
Otro nivel educacional
</td>
<td style="text-align:center;">
4593
</td>
<td style="text-align:center;">
3450
</td>
</tr>
</tbody>
</table>
</div>
<p>Plantee una prueba de hipótesis para estudiar si, la proporción de mujeres que tienen un nivel educacional distinto al de Escolar Completo, es no mayor igual a la proporción de Hombres que tienen un nivel educacional Escolar Completo. Utilice una confianza del 97.1%. Concluya utilizando el método del intervalo de confianza.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-83" class="exercise"><strong>Ejercicio 2.27  </strong></span>Se realizó un estudio con el fin de registrar la cantidad de personas morosas respecto al pago de contribuciones, y si estas tienen o no una enfermedad crónica asociada. Las frecuencias se aprecian en la siguiente tabla.</p>
<div style="border: 0px; overflow-x: auto; ">
<table class="table table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Moroso
</th>
<th style="text-align:center;">
No Moroso
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Con enfermedad
</td>
<td style="text-align:center;">
128
</td>
<td style="text-align:center;">
234
</td>
</tr>
<tr>
<td style="text-align:left;">
Sin enfermedad
</td>
<td style="text-align:center;">
340
</td>
<td style="text-align:center;">
260
</td>
</tr>
</tbody>
</table>
</div>
<p>A continuación.</p>
<ol style="list-style-type: decimal">
<li><p>Plantee una prueba de hipótesis para estudiar si, las proporciones de personas morosas y no morosas que tienen una enfermedad son distintas. Utilice una confianza del 79.7%. Concluya utilizando el método del valor - p.</p></li>
<li><p>Plantee una prueba de hipótesis para estudiar si, la proporción de personas con enfermedad que son morosas es no menor igual a la proporción de personas sin enfermedad que son morosas por menos de 0.2 unidades. Utilice una confianza del 91.2%. Concluya utilizando el método del intervalo de confianza.</p></li>
</ol>
</div>
</div>
<div id="ejercicios-unidad2" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Ejercicios<a href="PH.html#ejercicios-unidad2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación, desarrolle los ejercicios manualmente sin el uso de R, a menos que se indique lo contrario.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-84" class="exercise"><strong>Ejercicio 2.28  </strong></span>Un encargado de operaciones analiza el tiempo de carga de una aplicación móvil (segundos); se sabe que la desviación estándar poblacional es <span class="math inline">\(\sigma=2.0\)</span>. En una prueba piloto se recolectaron los tiempos de carga de 10 sesiones de uso: 18, 20, 19, 21, 17, 22, 20, 19, 18, 21. Con un nivel de significancia de 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es distinto de 20. Considere que <span class="math inline">\(Z_{1-0.05/2}=1.9599\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-85" class="exercise"><strong>Ejercicio 2.29  </strong></span>Un equipo de calidad controla el tiempo de respuesta (ms) de un servicio web; se conoce <span class="math inline">\(\sigma=10\)</span>. Durante un día se tomaron registros de respuesta en 10 solicitudes consecutivas: 205, 199, 201, 208, 202, 207, 203, 200, 204, 206. Con un nivel de significancia del 10% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para estudiar si el promedio poblacional es mayor a 200. Considere que <span class="math inline">\(Z_{1-0.10}=1.2816\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-86" class="exercise"><strong>Ejercicio 2.30  </strong></span>Un laboratorio registra la acidez de una bebida gaseosa (pH); se conoce <span class="math inline">\(\sigma=0.20\)</span>. En una inspección de calidad se midieron ocho lotes de producción con valores de pH: 3.42, 3.39, 3.41, 3.40, 3.38, 3.43, 3.37, 3.41. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para verificar si el pH promedio poblacional es menor a 3.40. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449, Z_{0.05}=-1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-87" class="exercise"><strong>Ejercicio 2.31  </strong></span>Una clínica mide la duración de consultas médicas (minutos); las varianzas poblacionales son desconocidas. En un día laboral se registraron las siguientes duraciones de atención en 8 pacientes: 12, 11, 13, 10, 12, 14, 11, 13. Con un nivel de significancia del 1% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es distinto de 12. Considere que <span class="math inline">\(t_{1-0.01/2,\,7}=3.4995\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-88" class="exercise"><strong>Ejercicio 2.32  </strong></span>Un analista de recursos humanos estudia las horas de capacitación recibidas por empleado en una semana; las varianzas poblacionales son desconocidas. Se recopilaron datos de 8 empleados: 5.0, 5.5, 4.8, 5.3, 5.1, 5.6, 5.2, 5.4. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para determinar si el promedio poblacional es mayor a 5.0. Considere que <span class="math inline">\(t_{1-0.05,\,7}=1.8946\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-89" class="exercise"><strong>Ejercicio 2.33  </strong></span>Un responsable de logística mide el tiempo de picking de pedidos (minutos); las varianzas poblacionales son desconocidas. En un turno se observaron los siguientes tiempos de preparación: 9.1, 8.7, 9.0, 8.8, 9.2, 8.9, 8.6. Con un nivel de significancia del 10% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es menor a 9.0. Considere que <span class="math inline">\(t_{1-0.10,\,6}=1.4400, t_{0.10,\,6}=-1.4400\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-90" class="exercise"><strong>Ejercicio 2.34  </strong></span>Dos procesos industriales (X e Y) producen piezas; se conocen <span class="math inline">\(\sigma_X=1.5\)</span> y <span class="math inline">\(\sigma_Y=2.0\)</span>. Para el proceso X se tomaron mediciones de resistencia: 52, 55, 54, 53, 56, 55, 54. Para el proceso Y se recolectaron mediciones en seis piezas: 50, 48, 49, 51, 47, 50. Con un nivel de significancia de 10% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si la diferencia de medias poblacionales es distinta de 0. Considere que <span class="math inline">\(Z_{1-0.10/2}=1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-91" class="exercise"><strong>Ejercicio 2.35  </strong></span>Dos líneas de ensamblaje (L1 y L2) tienen tiempos de armado (min). Se conocen <span class="math inline">\(\sigma_{L1}=0.9\)</span> y <span class="math inline">\(\sigma_{L2}=1.1\)</span>. En L1 se midieron los tiempos de seis productos: 12.1, 12.4, 11.9, 12.3, 12.0, 12.2. En L2 se midieron los tiempos de seis productos: 11.4, 11.6, 11.5, 11.7, 11.3, 11.6. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media de L1 supera a la de L2. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-92" class="exercise"><strong>Ejercicio 2.36  </strong></span>Dos aplicaciones móviles (A y B) registran latencia de carga (ms); se conocen <span class="math inline">\(\sigma_A=12\)</span> y <span class="math inline">\(\sigma_B=10\)</span>. Para la app A se registraron los tiempos: 210, 205, 198, 202, 207, 200, 203. Para la app B se registraron: 195, 197, 193, 198, 196, 194, 199. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media de A es menor que la de B. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449, Z_{0.05}=-1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-93" class="exercise"><strong>Ejercicio 2.37  </strong></span>Dos cursos universitarios (Ingeniería y Economía) rinden un test de conocimientos; las varianzas poblacionales son desconocidas pero se asumen iguales. En Ingeniería se obtuvieron puntajes: 72, 74, 75, 73, 76, 71. En Economía se obtuvieron: 68, 70, 69, 67, 71, 68. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las medias poblacionales son distintas. Considere que <span class="math inline">\(t_{1-0.05/2,\,10}=2.2281\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-94" class="exercise"><strong>Ejercicio 2.38  </strong></span>Dos plantas de producción (P1 y P2) comparan su productividad (unidades por hora); las varianzas poblacionales son desconocidas pero se asumen iguales. En P1 se registraron productividades: 105, 110, 108, 107, 109, 106. En P2 se registraron: 100, 98, 101, 99, 102, 100. Con un nivel de significancia del 3% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media de P1 supera a la de P2. Considere que <span class="math inline">\(t_{1-0.03,\,10}=2.2281\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-95" class="exercise"><strong>Ejercicio 2.39  </strong></span>Dos equipos de ventas (X e Y) reportan número de contratos logrados en un mes; las varianzas poblacionales son desconocidas pero se asumen iguales. Para X se recolectaron datos de 7 agentes: 15, 18, 16, 17, 19, 20, 18. Para Y se recolectaron datos de 7 agentes: 12, 14, 13, 15, 14, 13, 12. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media de X es menor que la de Y. Considere que <span class="math inline">\(t_{1-0.10,\,12}=1.3562, t_{0.10,\,12}=-1.3562\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-96" class="exercise"><strong>Ejercicio 2.40  </strong></span>Dos métodos de cultivo agrícola (X e Y) son evaluados en rendimiento (kg por parcela); las varianzas poblacionales son desconocidas y no se asumen iguales. Para X se registraron: 210, 215, 212, 218, 214. Para Y se registraron: 200, 205, 202, 199, 203. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las medias poblacionales son distintas. Considere que <span class="math inline">\(t_{1-0.05/2,\,8}=2.3060\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-97" class="exercise"><strong>Ejercicio 2.41  </strong></span>Dos programas de entrenamiento físico (M1 y M2) se comparan por reducción de tiempo en pruebas (s); las varianzas poblacionales son desconocidas y no se asumen iguales. En M1 se registraron mejoras: 62, 65, 63, 64, 66. En M2 se registraron: 58, 57, 59, 56, 60. Con un nivel de significancia del 3% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media de M1 supera a la de M2. Considere que <span class="math inline">\(t_{1-0.03,\,7}=2.3650\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-98" class="exercise"><strong>Ejercicio 2.42  </strong></span>Dos grupos de voluntarios (Control y Experimental) registran tiempo de reacción (ms); las varianzas poblacionales son desconocidas y no se asumen iguales. En el grupo Control se midieron tiempos: 220, 225, 218, 222, 219. En el grupo Experimental se midieron: 210, 212, 208, 211, 209. Con un nivel de significancia del 8% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media del grupo Control es menor que la del grupo Experimental. Considere que <span class="math inline">\(t_{1-0.08,\,8}=1.8595, t_{0.08,\,8}=-1.8595\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-99" class="exercise"><strong>Ejercicio 2.43  </strong></span>Dos modelos de batería (A y B) son comparados en tiempo de carga (min). Para el modelo A se midieron cargas: 120, 118, 122, 121, 119, 123. Para el modelo B se midieron: 115, 116, 117, 114, 115, 118. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las varianzas poblacionales son distintas. Considere que <span class="math inline">\(F_{1-0.05/2,\,5,\,5}=5.05, F_{0.05/2,\,5,\,5}=0.20\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-100" class="exercise"><strong>Ejercicio 2.44  </strong></span>Dos proveedores de insumos (X e Y) registran tiempos de entrega (días). En el proveedor X se observaron: 32, 34, 33, 35, 31, 36. En el proveedor Y se observaron: 28, 29, 30, 27, 31, 29. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la varianza de X es mayor que la de Y. Considere que <span class="math inline">\(F_{1-0.10,\,5,\,5}=3.33, F_{0.10,\,5,\,5}=0.30\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-101" class="exercise"><strong>Ejercicio 2.45  </strong></span>Dos equipos de producción (E1 y E2) reportan tiempos de set-up (min). En E1 se midieron duraciones: 15, 17, 16, 14, 18, 15. En E2 se midieron: 16, 16, 15, 17, 16, 18. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la varianza de E1 es menor que la de E2. Considere que <span class="math inline">\(F_{1-0.05,\,5,\,5}=5.05, F_{0.05,\,5,\,5}=0.20\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-102" class="exercise"><strong>Ejercicio 2.46  </strong></span>En una encuesta de mercado, 100 personas fueron consultadas sobre producto X y 60 declararon preferirlo, mientras que en otra encuesta a 120 personas sobre producto Y, 78 lo prefirieron. Con un nivel de significancia del 5% elabore una prueba de hipótesis para evaluar si la diferencia de proporciones poblacionales es distinta de 0. Considere que <span class="math inline">\(Z_{1-0.05/2}=1.9599\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-103" class="exercise"><strong>Ejercicio 2.47  </strong></span>En una campaña publicitaria, 150 clientes fueron encuestados y 90 eligieron la versión nueva, mientras que en otro grupo de 160 clientes 70 eligieron la versión antigua. Con un nivel de significancia del 5% elabore una prueba de hipótesis para verificar si la proporción de la versión nueva es mayor que la de la versión antigua. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-104" class="exercise"><strong>Ejercicio 2.48  </strong></span>En dos regiones se midió la adopción de un programa social. En la Región Norte 52 de 110 personas encuestadas declararon participar, mientras que en la Región Sur 70 de 130 manifestaron lo mismo. Con un nivel de significancia del 10% elabore una prueba de hipótesis para evaluar si la proporción de la Región Norte es menor que la de la Región Sur. Considere que <span class="math inline">\(Z_{1-0.10}=1.2816, Z_{0.10}=-1.2816\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-105" class="exercise"><strong>Ejercicio 2.49  </strong></span>Un analista de procesos evalúa el tiempo de arranque de servidores (segundos) tras una actualización nocturna; se conoce <span class="math inline">\(\sigma=3.0\)</span>. Durante una ventana de mantenimiento del viernes se registraron 10 arranques consecutivos del mismo clúster: 42, 41, 39, 44, 40, 43, 42, 41, 40, 44. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es distinto de 41. Considere que <span class="math inline">\(Z_{1-0.05/2}=1.9599\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-106" class="exercise"><strong>Ejercicio 2.50  </strong></span>Un laboratorio de control mide el contenido de cafeína (mg) de una bebida energética; se conoce <span class="math inline">\(\sigma=6\)</span>. En una corrida de producción del turno mañana se muestrearon 10 latas al azar de la línea de envasado: 83, 86, 90, 85, 88, 84, 87, 89, 86, 85. Con un nivel de significancia del 10% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para verificar si el promedio poblacional es mayor a 85. Considere que <span class="math inline">\(Z_{1-0.10}=1.2816\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-107" class="exercise"><strong>Ejercicio 2.51  </strong></span>Un área de calidad registra el porcentaje de humedad (puntos porcentuales) de paquetes sellados; se conoce <span class="math inline">\(\sigma=0.7\)</span>. En una ronda de muestreo al final del día se extrajeron 8 paquetes de diferentes estanterías del depósito: 7.1, 6.9, 7.0, 6.8, 7.2, 6.7, 7.0, 6.9. Con un nivel de significancia del 1% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es menor a 7.0. Considere que <span class="math inline">\(Z_{1-0.01}=2.3263, Z_{0.01}=-2.3263\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-108" class="exercise"><strong>Ejercicio 2.52  </strong></span>Una clínica odontológica registra la duración de limpiezas (minutos) en pacientes adultos; las varianzas poblacionales son desconocidas. En un bloque de atención de media mañana se midieron 9 procedimientos consecutivos realizados por el mismo profesional: 32, 35, 31, 33, 34, 30, 32, 33, 31. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es distinto de 32. Considere que <span class="math inline">\(t_{1-0.05/2,\,8}=2.3060\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-109" class="exercise"><strong>Ejercicio 2.53  </strong></span>Un departamento de TI registra horas de capacitación semanal por persona en modalidad e-learning; las varianzas poblacionales son desconocidas. Se levantaron datos al cierre del mes para 7 colaboradores seleccionados aleatoriamente: 6.0, 5.8, 6.1, 6.3, 6.2, 5.9, 6.4. Con un nivel de significancia del 10% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para verificar si el promedio poblacional es mayor a 6.0. Considere que <span class="math inline">\(t_{1-0.10,\,6}=1.4400\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-110" class="exercise"><strong>Ejercicio 2.54  </strong></span>Una bodega controla el tiempo de picking (min) en pedidos minoristas; las varianzas poblacionales son desconocidas. En un turno corto de alta demanda se observaron 8 pedidos seleccionados sistemáticamente cada 5 órdenes: 7.9, 8.1, 8.0, 7.8, 8.2, 7.7, 7.9, 8.0. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es menor a 8.0. Considere que <span class="math inline">\(t_{1-0.05,\,7}=1.8946, t_{0.05,\,7}=-1.8946\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-111" class="exercise"><strong>Ejercicio 2.55  </strong></span>Dos líneas de producción (X e Y) se comparan en diámetro de ejes (mm); se conocen <span class="math inline">\(\sigma_X=0.12\)</span> y <span class="math inline">\(\sigma_Y=0.10\)</span>. En la auditoría de control se tomaron 6 mediciones de ejes consecutivos de X: 10.04, 10.02, 10.01, 10.05, 10.03, 10.04, y 6 mediciones de Y en el mismo turno: 9.98, 10.00, 9.99, 9.97, 10.00, 9.98. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si la diferencia de medias poblacionales es distinta de 0. Considere que <span class="math inline">\(Z_{1-0.05/2}=1.9599\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-112" class="exercise"><strong>Ejercicio 2.56  </strong></span>Dos turnos (mañana y tarde) se comparan en tiempo de armado (min); se conocen <span class="math inline">\(\sigma_M=1.0\)</span> y <span class="math inline">\(\sigma_T=1.2\)</span>. En una semana de observación se cronometraron 6 productos por turno, mañana: 14.2, 14.1, 13.9, 14.0, 14.3, 14.1, y tarde: 13.6, 13.7, 13.8, 13.6, 13.9, 13.7. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media del turno mañana es mayor que la del turno tarde. Considere que <span class="math inline">\(Z_{1-0.10}=1.2816\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-113" class="exercise"><strong>Ejercicio 2.57  </strong></span>Dos sensores (A y B) miden temperatura ambiental (°C) en salas contiguas; se conocen <span class="math inline">\(\sigma_A=0.6\)</span> y <span class="math inline">\(\sigma_B=0.6\)</span>. Se tomaron 5 lecturas alternadas por sensor durante la misma franja horaria, A: 22.1, 22.0, 22.3, 22.2, 22.1, B: 22.4, 22.5, 22.6, 22.3, 22.5. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media de A es menor que la de B. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449, Z_{0.05}=-1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-114" class="exercise"><strong>Ejercicio 2.58  </strong></span>Dos talleres (T1 y T2) comparan puntajes de una prueba técnica estandarizada; las varianzas poblacionales son desconocidas pero se asumen iguales. En la misma semana, T1 aplicó la prueba a 6 estudiantes (78, 80, 79, 81, 77, 80) y T2 a otros 6 (74, 76, 75, 77, 76, 75). Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las medias poblacionales son distintas. Considere que <span class="math inline">\(t_{1-0.05/2,\,10}=2.2281\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-115" class="exercise"><strong>Ejercicio 2.59  </strong></span>Dos plantas (P1 y P2) evalúan rendimiento (unid/h); las varianzas poblacionales son desconocidas pero se asumen iguales. En un ciclo homogéneo de producción se registraron 6 horas por planta, P1: 92, 95, 93, 94, 96, 95, P2: 90, 89, 91, 90, 92, 91. Con un nivel de significancia del 1% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media de P1 supera a la de P2. Considere que <span class="math inline">\(t_{1-0.01,\,10}=2.7638\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-116" class="exercise"><strong>Ejercicio 2.60  </strong></span>Dos equipos (E1 y E2) comparan ventas diarias (miles) en sucursales equivalentes; las varianzas poblacionales son desconocidas pero se asumen iguales. Durante una semana comparativa se registraron 6 días por equipo, E1: 18, 19, 17, 20, 18, 19, E2: 19, 18, 20, 19, 21, 20. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media de E1 es menor que la de E2. Considere que <span class="math inline">\(t_{1-0.10,\,10}=1.3722, t_{0.10,\,10}=-1.3722\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-117" class="exercise"><strong>Ejercicio 2.61  </strong></span>Dos métodos de estudio (X e Y) se comparan en puntaje final de un módulo online; las varianzas poblacionales son desconocidas y no se asumen iguales. Con una muestra al cierre del módulo se obtuvieron X: 5.8, 6.0, 6.1, 5.9, 6.2 y Y: 5.5, 5.6, 5.7, 5.5, 5.8. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las medias poblacionales son distintas. Considere que <span class="math inline">\(t_{1-0.05/2,\,8}=2.3060\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-118" class="exercise"><strong>Ejercicio 2.62  </strong></span>Dos tratamientos (A y B) se comparan en reducción de colesterol (mg/dL) en pacientes con perfil similar; las varianzas poblacionales son desconocidas y no se asumen iguales. En un ensayo piloto se observaron A: 18, 22, 20, 21, 19 y B: 14, 15, 16, 13, 15. Con un nivel de significancia del 3% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la media de A supera a la de B. Considere que <span class="math inline">\(t_{1-0.03,\,7}=2.3650\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-119" class="exercise"><strong>Ejercicio 2.63  </strong></span>Dos grupos (Control e Intervención) miden tiempo de completar una tarea (s) en laboratorio; las varianzas poblacionales son desconocidas y no se asumen iguales. En una sesión doble se midieron Control: 48, 47, 49, 46, 48 e Intervención: 47, 46, 45, 47, 46. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la media del grupo Control es menor que la del grupo Intervención. Considere que <span class="math inline">\(t_{1-0.10,\,8}=1.8595, t_{0.10,\,8}=-1.8595\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-120" class="exercise"><strong>Ejercicio 2.64  </strong></span>Dos líneas de producto (L1 y L2) comparan la variabilidad en peso de empaques (g). Para una inspección rutinaria se tomaron 6 unidades de cada línea, L1: 101, 102, 100, 103, 101, 102 y L2: 99, 100, 100, 98, 99, 100. Con un nivel de significancia del 5% y asumiendo normalidad, elabore una prueba de hipótesis para estudiar si las varianzas poblacionales son distintas. Considere que <span class="math inline">\(F_{1-0.05/2,\,5,\,5}=5.05, F_{0.05/2,\,5,\,5}=0.20\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-121" class="exercise"><strong>Ejercicio 2.65  </strong></span>Dos proveedores (A y B) comparan la variabilidad del tiempo de despacho (horas) en rutas urbanas. Se monitorearon 6 despachos por proveedor en la misma franja horaria, A: 11, 12, 10, 11, 12, 11 y B: 9, 9, 10, 8, 9, 10. Con un nivel de significancia del 1% y asumiendo normalidad, elabore una prueba de hipótesis para verificar si la varianza de A es mayor que la de B. Considere que <span class="math inline">\(F_{1-0.01,\,5,\,5}=10.97\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-122" class="exercise"><strong>Ejercicio 2.66  </strong></span>Dos laboratorios (L1 y L2) evalúan la variabilidad en concentración (ppm) del mismo reactivo. Se tomaron 6 réplicas independientes en cada laboratorio durante el mismo día, L1: 50.1, 50.3, 50.2, 50.0, 50.2, 50.1 y L2: 50.4, 50.5, 50.3, 50.6, 50.4, 50.5. Con un nivel de significancia del 10% y asumiendo normalidad, elabore una prueba de hipótesis para evaluar si la varianza de L1 es menor que la de L2. Considere que <span class="math inline">\(F_{1-0.10,\,5,\,5}=3.33, F_{0.10,\,5,\,5}=0.30\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-123" class="exercise"><strong>Ejercicio 2.67  </strong></span>En dos ciudades se midió la preferencia por un sistema de transporte mediante encuestas presenciales. En Ciudad Norte respondieron 72 de 140 a favor y en Ciudad Sur 60 de 120 a favor. Con un nivel de significancia del 5% elabore una prueba de hipótesis para evaluar si las proporciones poblacionales son distintas. Considere que <span class="math inline">\(Z_{1-0.05/2}=1.9599\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-124" class="exercise"><strong>Ejercicio 2.68  </strong></span>En una prueba A/B de una aplicación móvil, 84 de 200 usuarios con la versión nueva completaron la compra y 70 de 210 con la versión antigua lo hicieron durante la misma semana de campaña. Con un nivel de significancia del 10% elabore una prueba de hipótesis para verificar si la proporción de la versión nueva es mayor que la de la versión antigua. Considere que <span class="math inline">\(Z_{1-0.10}=1.2816\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-125" class="exercise"><strong>Ejercicio 2.69  </strong></span>En dos zonas de venta se midió conversión a compra con el mismo script comercial. Zona Este: 45 de 90 casos con conversión, Zona Oeste: 58 de 125 casos con conversión. Con un nivel de significancia del 5% elabore una prueba de hipótesis para evaluar si la proporción de la Zona Este es menor que la de la Zona Oeste. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449, Z_{0.05}=-1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-126" class="exercise"><strong>Ejercicio 2.70  </strong></span>Un responsable de manufactura mide tiempos de cambio de formato (min) en una línea automatizada; se conoce <span class="math inline">\(\sigma=2.5\)</span>. En una semana de pruebas se observaron 10 cambios seleccionados aleatoriamente entre turnos: 19, 18, 20, 22, 17, 21, 20, 19, 18, 21. Con un nivel de significancia del 3% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para evaluar si el promedio poblacional es distinto de 20. Considere que <span class="math inline">\(Z_{1-0.03/2}=2.1701\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-127" class="exercise"><strong>Ejercicio 2.71  </strong></span>Un control de calidad mide la dureza (HRC) de piezas templadas; se conoce <span class="math inline">\(\sigma=1.8\)</span>. En una inspección al azar se registraron 8 piezas consecutivas de la misma cuba: 58.1, 57.9, 58.4, 58.2, 58.0, 58.3, 58.1, 58.2. Con un nivel de significancia del 5% y asumiendo normalidad de los datos, elabore una prueba de hipótesis para verificar si el promedio poblacional es mayor a 58.0. Considere que <span class="math inline">\(Z_{1-0.05}=1.6449\)</span>. El valor-p debe calcularse en R. Utilice todos los métodos de rechazo.</p>
</div>

</div>
</div>
<h3>Referencias<a href="referencias.html#referencias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0" line-spacing="2">
<div id="ref-anderson" class="csl-entry">
Anderson, D. R., Sweeney, D. J., &amp; Williams, T. A. (2008). <em>Estadística para administración y economía</em> (10a ed). Cengage Learning.
</div>
<div id="ref-Devore" class="csl-entry">
Devore, J. L. (2008). <em>Probability and statistics for engineering and the sciences</em> (7th ed). Thomson/Brooks/Cole.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intervalos-de-confianza.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regresion-lineal.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": true,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": true,
    "all": false
  },
  "fontsettings": false,
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["est2+inferencia.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": null
  },
  "info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
