\begin{center}
{\bf \Large{Taller de práctica Examen}}\\
\end{center}

\section*{Parte 1}

Sean $X_1, \ldots, X_k$ y $Y$ variables aleatorias de un muestra de tamaño $n$. Considere el siguiente modelo de regresión lineal múltiple:

$$
Y_i = \beta_0 + \beta_1X_1 +\cdots + \beta_kX_k + \epsilon_i, \epsilon_i \overset{iid}{\sim} N(0, \sigma^2)
$$

Demuestre que:

\begin{enumerate}
  \item
  \item 
  \item 
\end{enumerate}

\section*{Parte 2}

La siguiente base contiene datos relacionados a la contratación de seguros médicos. Las columnas de la base de datos son las siguientes:

\begin{itemize}
    \item \texttt{age}: edad en años del beneficiario principal.
    \item \texttt{sex}: sexo (``female'', ``male'') del beneficiario principal.
    \item \texttt{bmi}: índice de masa corporal del beneficiario principal.
    \item \texttt{children}: número de niños cubiertos por el seguro.
    \item \texttt{smoker}: indica si es (``yes'') o no (``no'') fumador el beneficiario principal.
    \item \texttt{region}: el área residencial del beneficiario en los EEUU, ``northeast'', ``southeast'', ``southwest'', ``northwest''.
    \item \texttt{charges}: costos médicos (en dólares) individuales facturados por el seguro de salud.
\end{itemize}
    
A continuación, se despliega la siguiente salida de R asociada a un modelo de regresión lineal múltiple

<<echo=F>>=
data = read.csv("https://raw.githubusercontent.com/Dfranzani/Bases-de-datos-para-cursos/main/2023-1/insurance.csv")
data$sex = factor(data$sex, levels =c("male", "female"))
data$smoker = factor(data$smoker, levels =c("yes", "no"))
modelo = lm(charges ~ age + sex + region + smoker, data = data)
summary(modelo)
@

\begin{enumerate}
\item Escriba la ecuación de regresión poblacional.
\item Escriba la ecuación de regresión ajustada.
\item Interprete los parámetros estimados.
\item Estudie las pruebas de hipótesis de no nulidad y no nulidad conjunta. Utilice una confianza del 95\%. Escriba las hipótesis involucradas.
\item Interprete el $R^2$ ajustado, y comente porque no es adecuado usar el $R^2$ para interpretar un modelo de regresión lineal múltiple.
%\item Explique el principio de la parsimonia.

\item Utilice la siguiente tabla (que contiene un resumen de salidas en R) para estudiar los supuestos de Homocedasticidad, Independencia y Normalidad del modelo de la pregunta anterior. Indique la fila del código seleccionado para cada supuesto, justificando su elección, además, escriba las pruebas de hipótesis involucradas e interprete utilizando una confianza del 95\%. 
    
<<echo=FALSE, results='asis',message=F>>=
library(lmtest)
library(nortest)


test_latex = function(prueba){
    type = ifelse(is.null(prueba$alternative), "-", prueba$alternative)
    words = strsplit(prueba$data.name,"~")
    if(length(words[[1]]) == 2){
        words = paste0("$\\text{", words[[1]][1], "}\\sim \\text{", words[[1]][2],"}$")
    }
    if(grepl("fitted.values", words)){
        words = "modelo\\$fitted.values"
    }
    
    test = sub(" test", "", prueba$method)
    test = sub("studentized", "", test)
    test = sub("One-sample", "", test)
    test = sub("normality", "", test)
    return(c(test, round(prueba$p.value,7), words, type))
}

tabla = matrix(c(
    test_latex(shapiro.test(x = modelo$fitted.values)),
    test_latex(shapiro.test(x = rstandard(modelo))),
    test_latex(ad.test(x = modelo$fitted.values)),
    # test_latex(ks.test(data$charges, "pnorm", 0, 1)),
    test_latex(dwtest(formula = age ~ charges + sex + region + smoker, data = data, alternative = "two.sided")),
    test_latex(dwtest(formula = charges ~ age + region + smoker, data = data, alternative = "two.sided")),
    test_latex(dwtest(formula = charges ~ age + sex + region + smoker, data = data, alternative = "two.sided")),
    test_latex(bptest(formula = age ~ charges + sex + region + smoker, data = data)),
    test_latex(bptest(formula = charges ~ age + sex + region + smoker, data = data)),
    test_latex(bptest(formula = charges ~ age + region + smoker, data = data))
), byrow = T, ncol = 4)

tabla = cbind(1:dim(tabla)[1], tabla)

set.seed(2024)
tabla[,3] = round(runif(n=dim(tabla)[1], min=0, max=0.1), 4)

tabla = structure(tabla, .Dim = c(dim(tabla)))

cat(kableExtra::kbl(tabla, align = 'l', booktabs = TRUE, linesep = "",
    escape = FALSE, format = "latex",
    col.names = c("","Prueba de hipótesis", "Valor-p", "Datos utilizados", "Hipótesis alternativa")) |>
  kable_styling(latex_options = c("HOLD_position","striped")))
@


\item Explique los siguientes códigos asociados a la base de datos. Sea riguroso en su explicación, escriba toda la terminología estadística involucrada. En particular explique/defina lo siguiente:
\begin{itemize}
    \item Prueba de hipótesis ($H_0$ y $H_1$).
    \item Explique las variables involucradas en las pruebas (incluyendo los filtros aplicados).
    \item Interprete el valor-p y el intervalo de confianza como criterio de rechazo. Elabore una conclusión asociada a la prueba. Utilice una confianza del 95\%.
\end{itemize}
\begin{enumerate}

\item Código 1
<<>>=
var.test(x = data$charges[data$smoker == "yes"], 
         y = data$charges[data$smoker == "no"],
         conf.level = 0.932,
         alternative = "two.sided")
@

\item Código 2
<<>>=
t.test(x = data$charges[data$smoker == "yes"], 
         y = data$charges[data$smoker == "no"],
         conf.level = 0.932,
         mu = 22090,
         alternative = "greater",
         var.equal = T)
@

\item ¿Que relación tiene el código 1 con el 2 del ítem \textit{a)} y \textit{b)} respectivamente? ¿Habría que corregir algo para que estuviesen bien planteados ambos en un mismo análisis?

% \item Interprete las siguientes salidas asociadas a intervalos de confianza y predicción.
% 
% <<>>=
% new.df = data.frame("age"= 55, "sex" = "male", region = "southwest", smoker = "yes")
% predict.lm(modelo, newdata = new.df, interval = "prediction")
% @
% 
% <<>>=
% new.df = data.frame("age"= 65, sex = "female", region = "southwest", smoker = "no")
% predict.lm(modelo, newdata = new.df, interval = "confidence")
% @

\end{enumerate}
\end{enumerate}